[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Рассмотрим функцию `sleep(d)`, которая приостанавливает выполнение на заданную продолжительность:

```rust
let futs: Vec<_> = [1, 2, 3].iter().map(|n| async move {
  sleep(Duration::from_secs(5)).await;
  n + 1
}).collect();

for fut in futs {
  let n = fut.await;
  println!("{n}");
}
```

При выполнении примерно сколько секунд займёт этот код?
"""
prompt.distractors = ["5", "0"]
answer.answer = "15"
context = """
Без использования функции вроде `join_all`, футуры не будут выполняться конкурентно. Поэтому этот код займёт 15 секунд (по 5 секунд на каждый элемент списка).
"""
id = "68680e2e-7a9f-4cee-8080-70e57fe5a2b3"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Предположим, вы проектируете служебную функцию со следующей спецификацией:

> `map_stringify` принимает два аргумента: вектор входных данных и асинхронную функцию, преобразующую вход в выход,
> где выходы могут быть преобразованы в строки.
> `map_stringify` возвращает вектор строк, полученных из выходов.

Какая сигнатура типа функции лучше всего соответствует этой спецификации?
"""
prompt.distractors = [
"""
```rust
async fn map_stringify(
  inputs: Vec<String>, f: impl Future<Output = String>
) -> Vec<String>
```
""",
"""
```rust
fn map_stringify<I, O, F>(
  inputs: Vec<I>, f: impl Fn(I) -> O,
) -> Vec<impl Future<Output = String>>
where
  O: ToString,  
```
""",
"""
```rust
async fn map_stringify<I, F>(
  inputs: Vec<I>, f: impl Fn(I) -> F, 
) -> Vec<String>
where
  F: Future + ToString,
```
"""]
answer.answer = """
```rust
async fn map_stringify<I, O, F>(
  inputs: Vec<I>, f: impl Fn(I) -> F, 
) -> Vec<String>
where
  O: ToString,
  F: Future<Output = O>,
```
"""
context = """
Вот одна из реализаций указанной функции:

```rust
async fn map_stringify<I, O, F>(
  f: impl Fn(I) -> F, inputs: Vec<I>
) -> Vec<String>
where
  O: ToString,
  F: Future<Output = O>,
{
  let f = &f;
  let futs = inputs
    .into_iter()
    .map(|input| async move { f(input).await.to_string() });
  futures::future::join_all(futs).await
}
```
"""
id = "b42a9c5b-bfe7-4d6f-967a-f8ff2a6faa0d"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Предположим, вы пишете программу, которой нужно выполнять асинхронный код, но каждые 500ms проверять, не требуется ли остановить вычисление.
Какой вспомогательной функцией лучше всего выполнить эту задачу?
"""
prompt.distractors = [
  "`join`",
  "`yield`",
  "`spawn` / `spawn_task`"
]
answer.answer = "`race` / `select`"
context = """
Например, вы можете в цикле выполнять `select` между долгим фучером и фучером сна, который завершится через 500ms.
"""
id = "7da21e95-8e03-412b-8c4d-90ccfc8c6802"