[[questions]]
type = "MultipleChoice"
prompt.prompt = "Учитывая футур `f`, какой из следующих вариантов лучше всего описывает работу `f.await`?"
prompt.distractors = [
  "Он вызывает `f.poll()` один раз, который блокирует на месте, пока `f` не будет готов",
  "Он вызывает `f.poll()` в цикле, выходя, если `f` готов, или немедленно проводя повторный опрос, если `f` не готов",
  "Он вызывает `f.push(...)` один раз, который выполняет обратный вызов, содержащий оставшийся код после `f.await`, как только `f` будет готов"
]
answer.answer = "Он вызывает `f.poll()` в цикле, выходя, если `f` готов, или возвращая управление асинхронному рантайму, если `f` не готов"
context = """
Rust использует модель на основе опроса (poll-based) для выполнения футуров. Точка await разворачивается в цикл, который многократно вызывает `.poll()`, 
и уступает управление асинхронному рантайму после каждой неудачной попытки опроса, чтобы позволить другому асинхронному коду выполняться. Рантайм может позже
"разбудить" код `f.await`, чтобы снова провести опрос `f`.
"""
id = "c4d90f3c-7286-4272-921c-241b266e9f91"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Представьте, что Rust не требует, чтобы футуры были закреплены в памяти (pinned) для их опроса.
Какая из следующих асинхронных функций потенциально может привести к неопределённому поведению, если её не закрепить?
"""
prompt.distractors = [
"""
```rust
async fn example(x: &i32) -> i32 {
    sleep(Duration::from_secs(1)).await;
    *y
}
```
""",
"""
```rust
async fn example(x: Vec<i32>) -> i32 {
    sleep(Duration::from_secs(1)).await;
    x[0]
}
```
""",
"""
```rust
async fn example() -> i32 {
    let x = 0;
    sleep(Duration::from_secs(1)).await;
    x
}
```
""",  
]
answer.answer = """
```rust
async fn example(x: i32) -> i32 {
    let y = &x;
    sleep(Duration::from_secs(1)).await;
    *y
}
```
"""
context = """
Основная проблема, решаемая закреплением в памяти (pinning), — это самореференция, или футур, который содержит указатель на самого себя. 
Это происходит, когда асинхронный блок содержит локальную переменную, которая ссылается на другую локальную переменную внутри футура.
Здесь это было бы `y = &x`.
"""
id = "bc8b4acb-d111-4fec-b89a-e5d1bc77c8f2"