[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Типаж `Stream` наиболее аналогичен какому неасинхронному типажу в стандартной библиотеке Rust?
"""
prompt.distractors = ["`Write`", "`Index`", "`Sync`"]
answer.answer = "`Iterator`"
context = """
Типаж `Stream` предоставляет асинхронную версию итератора Rust.
"""
id = "f94a87f0-a4d6-4cd6-bcee-dfcc606f8ec2"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Предположим, у вас есть поток, производящий последовательность `["A", "B", "C"]`, и другой поток, производящий последовательность ["D", "E", "F"].
Вы не знаете, когда каждый поток выдаст каждый символ, только что это происходит в указанных последовательностях.
Рассмотрите слияние этих потоков и вывод каждого символа. Затем выберите все следующие строки вывода, которые могут быть напечатаны.
"""
prompt.distractors = [
  "ACBDEF",
  "CFBEAD"
]
answer.answer = [
  "ABDEFC",
  "DEFABC"
]
context = """
Слияние всегда будет соблюдать порядок в каждом потоке, поэтому, например, "B" не может появиться перед "C".
"""
id = "84452eff-13df-4fcb-91ea-1f504d5bfaf0"