[[questions]]
type = "MultipleChoice"
prompt.prompt = "Если вы хотите дождаться завершения фьючерса в неасинхронном коде, что следует сделать?"
prompt.distractors = [
  "Поставить `.await` сразу после фьючерса",
  "Передать фьючерс встроенному асинхронному рантайму Rust",
  "Обернуть фьючерс в блок `async` и дождаться (`.await`) блока",  
]
answer.answer = "Передать фьючерс стороннему асинхронному рантайму"
context = """
Rust не позволяет использовать `.await` вне блоков или функций `async`. Rust также не имеет встроенного асинхронного рантайма.
Вам следует использовать сторонний асинхронный рантайм, такой как `tokio` или `trpl`. 
"""
id = "de2a5023-dd5c-412e-8425-c8ed638f18f0"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
В какой тип-сигнатуру превращается после десугаризации (desugars) приведённая ниже асинхронная функция?

```rust
async fn calculate(nums: &[i32]) -> i32 {
  /* ... */
}
```
"""
prompt.distractors = [
  """
```rust
fn calculate<'a>(nums: &'a [i32], output: &mut impl Future<Output = i32> + 'a);
```
  """,
  """
```rust
fn calculate(nums: &'_ [i32]) -> i32 as Future;
```
  """,
  """
```rust
fn calculate() -> impl for<'a> Future<Input = &'a [i32], Output = i32> + 'a;
```
  """
]
answer.answer = """
```rust
fn calculate<'a>(nums: &'a [i32]) -> impl Future<Output = i32> + 'a;
```
"""
context = """
Асинхронная функция возвращает анонимный тип, который реализует типаж `Future`, чей результат (output) равен возвращаемому типу функции. 
Здесь это представлено как `impl Future<Output = i32>`. Фьючерс захватывает любые времена жизни (lifetimes) в аргументах функции.
Поэтому возвращаемый тип имеет ограничение `+ 'a`, а тип входного среза — `&'a [i32]`. Это указывает, что срез должен жить как минимум столько же, сколько живет фьючерс, который его захватывает.
"""
id = "9c000322-464b-4d34-9e30-55591f9283d2"