[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Рассмотрим следующую функцию:

```rust
async fn print_letters() {
  let a = async { print!("A"); };
  let b = async { print!("B"); };
  let c = async { print!("C"); };
  c.await;
  b.await;
  a.await;
}
```

Какие из следующих строк могут быть выведены после выполнения `print_letters().await`?
"""
prompt.distractors = ["`ABC`", "`BCA`", "`ACB`"]
answer.answer = ["`CBA`"]
context = """
Эта программа обладает детерминированным поведением. Выводы не выполняются, пока асинхронные блоки не будут ожидаемы (await).
Блоки ожидаются в порядке `c`/`b`/`a`, поэтому программа выведет только `CBA`.
"""
id = "8f62c158-525a-43a2-aa6a-0cc106cada10"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Предположим, что у вас есть вспомогательная функция `wait_all(a, b)` со следующим поведением:
* `wait_all` гарантирует, что `a` и `b` будут выполнены до завершения.
* `wait_all` не даёт гарантий относительно справедливости или начального порядка выполнения.

Тогда, учитывая следующий код:

```rust
async fn print_letters() {
  let fut1 = async { 
    print!("A");
    sleep().await;
    print!("B");
  };
  let fut2 = async {
    print!("C");
    sleep().await;
    print!("D");
  }
  wait_all(fut1, fut2).await;
}
```

Какие из следующих строк могут быть выведены после выполнения `print_letters().await`?
"""
prompt.distractors = ["`DABC`"]
answer.answer = [
  "`ABCD`", "`CADB`", "`ACBD`"
]
context = """
Гипотетический примитив `wait_all` похож на `join`, но даёт меньше гарантий. Учитывая только спецификацию из этой задачи, любая интерливинг (перемежение) двух фьючерсов является допустимым. Единственный недопустимый вывод — это тот, который инвертирует порядок выполнения программы, т.е. `DABC`, где `D` выводится перед `C`.
"""
id = "4b28f13e-9781-4d29-b886-7639fa527f36"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Предположим, что у вас есть канал обмена сообщениями `channel()`, который является неблокирующим и *ограниченным* (bounded), 
что означает, что `send` возвращает фьючерс, который завершается, когда в канале появится место.
Предположим также, что у вас есть функция `join(a, b)`, которая *справедливо* ожидает завершения обоих своих аргументов.
Тогда, учитывая этот асинхронный код:

```rust
let (tx, mut rx) = channel(16);
let recv_fut = rx.recv();
let send_fut = tx.send(0);
let (n, _) = join(recv_fut, send_fut).await;
println!("{}", n.unwrap());
```

Что произойдет в результате выполнения этого кода?
"""
prompt.distractors = [
  "Программа выведет `0` и зациклится навсегда",
  "Программа ничего не выведет и зациклится навсегда",
  "Программа паникует"
]
answer.answer = "Программа выведет `0` и завершится"
context = """
Поскольку канал неблокирующий, мы можем создать будущее на приём (recv future) перед отправкой, не зацикливаясь навсегда.
"""
id = "e23b7c48-3780-44e7-8ea4-df35032548a1"