[[questions]]
id = "87c3b09e-84d3-49d7-8680-0b2d068a7fc5"
type = "ShortAnswer"
prompt.prompt = "Каждая исполняемая программа на Rust должна содержать функцию с именем:"
answer.answer = "main"
context = """
В вашей программе вы добавляете функцию main так:

```
fn main() {
  // ваш код здесь
}
```
"""

[[questions]]
id = "0d78d302-eb3d-4ac7-a1ac-f2d661810744"
type = "MultipleChoice"
prompt.prompt = """
Предположим, у вас есть следующая программа в файле `hello.rs`:

```
fn main() {
  println!("Hello world!");
}
```

Если вы затем выполните команду `rustc hello.rs` из командной строки. Какое утверждение лучше всего описывает, что происходит дальше?
"""
answer.answer = "`rustc` создаёт бинарный исполняемый файл с именем `hello`"
prompt.distractors = [
  "`rustc` выведет ошибку, так как это недопустимая программа",
  "`rustc` выполняет программу и выводит `Hello world!`",
  "`rustc` переформатирует `hello.rs` в соответствии с руководством по стилю Rust"
]
context = """
Запуск `rustc` проверяет и компилирует вашу программу, но не выполняет её.
"""