[[questions]]
id = "6286342a-84c1-47c5-bfd2-f34b51df813c"
type = "ShortAnswer"
prompt.prompt = "Как называется инструмент командной строки для управления версией Rust на вашей машине?"
answer.answer = "rustup"
context = """
Например, вы можете написать `rustup update`, чтобы получить последнюю версию Rust.
"""