[[questions]]
id = "c1b7cc2e-b5fb-4b67-b0bb-600d82931f08"
type = "MultipleChoice"
prompt.prompt = """
Представьте, что вы только что скачали проект Cargo и выполнили `cargo run` в командной строке. Какое утверждение НЕ верно относительно того, что происходит дальше?
"""
answer.answer = "Cargo следит за изменениями файлов и повторно запускает бинарный файл при изменении"
prompt.distractors = [
  "Cargo загружает и собирает все зависимости проекта",
  "Cargo собирает проект в бинарный файл в каталоге `target/debug`",
  "Cargo выполняет бинарный файл проекта"
]
context = """
По умолчанию Cargo не следит за изменениями файлов. Но для этой цели вы можете использовать плагины, такие как [cargo-watch](https://crates.io/crates/cargo-watch).
"""