[[questions]]
id = "5ae11501-25d9-4b94-8e88-aa1c2122779f"
type = "MultipleChoice"
prompt.prompt = """
Истина/Ложь: выполнение этих двух фрагментов кода даёт одинаковое значение для `x`.

Фрагмент 1:
```
let x = if cond { 1 } else { 2 };
```

Фрагмент 2:
```
let x;
if cond {
  x = 1;
} else {
  x = 2;
}
```

(Примечание: оба фрагмента компилируются!)
"""
answer.answer = "Истина"
prompt.distractors = [ "Ложь" ]
context = """
Первое if-выражение — это более лаконичный способ представить поведение второго if-оператора.

Обратите внимание, что Rust **не требует** объявлять `x` изначально с `let mut` во втором фрагменте.
Это потому, что Rust может определить, что `x` присваивается только один раз, поскольку выполняется только одна ветвь 
if-оператора.
"""

[[questions]]
id = "4e07358c-b318-49cb-8210-fbed7ed50e23"
type = "Tracing"
prompt.program = """
fn main() {
  let x = 1;
  let y = if x { 0 } else { 1 }; 
  println!("{y}");
}
"""
answer.doesCompile = false
answer.lineNumber = 3
context = """
Условие в if-выражении должно быть логическим значением. Rust не имеет понятий "истинно" или "ложно" для небулевых значений.
"""