[[questions]]
id = "e582f00a-2f28-46e4-ae1b-77fd223cca4f"
type = "MultipleChoice"
prompt.prompt = "Наибольшее число, представимое типом `i128`, это:"
answer.answer = "2<sup>127</sup> - 1"
prompt.distractors = [
  "2<sup>128</sup>",
  "2<sup>128</sup> - 1",
  "2<sup>127</sup>",
]
prompt.answerIndex = 3
context = """
В общем случае, знаковое число с *n* битами может представлять числа в диапазоне от -(2<sup>n - 1</sup>) до 2<sup>n - 1</sup> - 1.
"""

[[questions]]
id = "3a92246b-a43c-4658-980b-335d7632ddcb"
type = "MultipleChoice"
prompt.prompt = "Если `x : u8 = 0`, что произойдет при вычислении `x - 1`?"
answer.answer = "Это зависит от режима компилятора." 
prompt.distractors = [
  "Это всегда вызовет панику.",
  "Это всегда вернет 255.",
]
context = """
Это выражение вызовет панику в режиме отладки и вернет 255 в режиме выпуска.
"""

[[questions]]
id = "9bcac1a1-d2df-4a51-b399-7fd8a6042cc2"
type = "Tracing"
prompt.program = """
fn main() {
  let x: fsize = 2.0;
  println!("{x}");
}
"""
answer.doesCompile = false
answer.lineNumber = 2
context = """
Тип `fsize` не существует. Числа с плавающей точкой должны быть либо `f32`, либо `f64`.
"""