[[questions]]
id = "30212501-00d5-4ef6-838f-3df5112ee7ed"
type = "Tracing"
prompt.program = """
fn main() {
  let message = "The temperature today is:";
  let x = [message, 100];
  println!("{} {}", x[0], x[1]);
}
"""
answer.doesCompile = false
answer.lineNumber = 3
context = """
Массив может содержать элементы только одного типа. Синтаксис `[message, 100]` создаёт массив с двумя элементами.
Переменная `message` — это строка, а константа `100` — число.
"""

[[questions]]
id = "4e632a23-24cc-4c29-8935-cf6b62c3764b"
type = "Tracing"
prompt.program = """
fn main() {
  let t = ([1; 2], [3; 4]);
  let (a, b) = t;
  println!("{}", a[0] + t.1[0]); 
}
"""
answer.doesCompile = true
answer.stdout = "4"
context = """
Синтаксис `[x; y]` объявляет массив с `y` копиями значения `x`. Синтаксис `(a, b)` деструктурирует `t` и связывает `a` с `[1; 2]`. 
Синтаксис `t.1` ссылается на второй элемент `t`, который равен `[3; 4]`.
"""