[[questions]]
id = "a48e524e-852c-400c-ae68-5c76a6761596"
type = "MultipleChoice"
prompt.prompt = "Какое из следующих утверждений верно относительно различий между использованием `let` и `const` для объявления переменной?"
answer.answer = "`const` можно использовать в глобальной области видимости, а `let` — только внутри функции"
prompt.distractors = [
  "Это просто разные синтаксисы для объявления переменных с одинаковой семантикой",
  "Компилятор выдаст ошибку, если имя `const`-переменной не записано в `UPPER_SNAKE_CASE`",
  "`const` можно присвоить только литералу, а не выражению, содержащему вычисления"
]

[[questions]]
id = "d209784f-cc52-4451-8049-ad204e89d587"
type = "Tracing"
prompt.program = """
const TWO: u32 = 1 + 1;
fn main() {
  println!("{TWO}");
}
"""
answer.doesCompile = true
answer.stdout = "2"
context = """
`const`-переменные можно определять вне функции и выполнять ограниченные формы вычислений.
"""