[[questions]]
id = "8bd8d8bc-e61e-48c7-ba78-0c89339e5995"
type = "MultipleChoice"
prompt.prompt = "Какое утверждение лучше всего описывает, что значит, если переменная `x` является неизменяемой?"
answer.answer = "`x` не может быть изменена после присвоения значения."
prompt.distractors = [
  "`x` хранится в неизменяемой области памяти.",
  "После определения `x` может быть изменена не более одного раза.",
  "Вы не можете создать ссылку на `x`."
]
context = """
Неизменяемая означает «не изменяемая» или неизменяемая.
"""

[[questions]]
id = "dcf53c67-b3c9-4c54-8da0-90749cc669e8"
type = "ShortAnswer"
prompt.prompt = "Какое ключевое слово используется после `let`, чтобы указать, что переменная может быть изменена?"
answer.answer = "mut"
context = """
Например, вы можете сделать изменяемую переменную `x`, написав: `let mut x = 1`.
"""

[[questions]]
id = "77f9f143-45a6-4f08-bd87-72bc50c00693"
type = "Tracing"
prompt.program = """
fn main() {
  let x = 1;
  println!("{x}");
  x += 1;
  println!("{x}");
}
"""
answer.doesCompile = false
answer.lineNumber = 4
context = """
Это ошибка компиляции, потому что строка 4 пытается изменить `x`, когда `x` не помечена как `mut`.
"""