[[questions]]
id = "5d774a01-8604-4386-8d81-498496ccd96c"
type = "MultipleChoice"
prompt.prompt = """
Какое из следующих утверждений наилучшим образом описывает разницу между стеком и кучей?
"""
answer.answer = "Стек хранит данные, связанные с конкретной функцией, в то время как куча хранит данные, которые могут пережить функцию"
prompt.distractors = [ 
  "Стек может хранить указатели на данные, хранящиеся в куче, в то время как куча хранит только данные без указателей",
  "Стек хранит неизменяемые данные, в то время как куча хранит изменяемые данные.",
  "Стек хранит данные, которые можно скопировать, в то время как куча хранит данные, которые нельзя скопировать."
]
context = """
Кадры в стеке связаны с конкретной функцией и освобождаются при возврате из функции.
Данные в куче могут существовать неограниченно долго. Обратите внимание, что и данные в стеке, и в куче могут быть изменяемыми и могут быть скопируемыми. Куча может содержать указатели (даже на стек, как мы увидим позже).
"""

[[questions]]
id = "4c953b2d-65bf-4dab-bbbb-14c9b15a690e"
type = "ShortAnswer"
prompt.prompt = """
Рассмотрим выполнение следующего фрагмента кода, конечное состояние показано:

```aquascope,interpreter
#fn main() {
let a = Box::new(15);
let b = a;
let c = Box::new(15);`[]`
#}
```

В конечном состоянии, сколько копий числа `15` существует где-либо в памяти? Напишите ваш ответ в виде цифры, например, 0 или 1.
"""
answer.answer = "2"
context = """
Два box'а содержат две копии числа 15. Присваивание `let b = a` копирует указатель на кучу, но не само число в куче.
"""