[[questions]]
id = "7fbda6e4-dca7-458e-ab52-fab03181f90b"
type = "MultipleChoice"
prompt.prompt = """
Рассмотрим переменные `s2` и `s3` в следующей программе. Эти две переменные будут расположены в памяти в стековом фрейме для `main`. У каждой переменной есть размер в памяти на стеке, *не включая* размер указываемых данных. Какое утверждение о размерах `s2` и `s3` верно?

```
fn main() {
  let s = String::from("hello");
  let s2: &String = &s;
  let s3: &str = &s[..];
}
```
"""
answer.answer = "`s3` занимает больше байтов, чем `s2`"
prompt.distractors = [
  "`s3` занимает то же количество байтов, что и `s2`",
  "`s3` занимает меньше байтов, чем `s2`"
]
context = """
Тип `&String` — это обычная ссылка, состоящая из одного указателя, поэтому 8 байт на 64-битной архитектуре. Тип `&str` — это специальная ссылка-срез, которая состоит из указателя *и* длины, поэтому 16 байт. Следовательно, `s3` типа `&str` использует больше памяти, чем `s2` типа `&String`. Вы можете проверить это самостоятельно с помощью [`std::mem::size_of`](https://doc.rust-lang.org/std/mem/fn.size_of.html), например:

```rust
fn main() {
  println!(
    "&String={} &str={}",
    std::mem::size_of::<&String>(),
    std::mem::size_of::<&str>(),
  );
}
```

Также обратите внимание, что Rust неявно преобразует ссылки на строки либо в `&String`, либо в `&str` в зависимости от контекста ссылки. Поэтому выражение `&s` производит два разных значения в зависимости от ожидаемого типа `&s`.
"""

[[questions]]
id = "adcfc154-03bd-470a-bacb-b3cad97cfc7f"
type = "Tracing"
prompt.program = """
fn main() {
  let mut s = String::from("hello");
  for &item in s.as_bytes().iter() {
    if item == b'l' {
      s.push_str(" world");
    }
  }
  println!("{s}");
}
"""
answer.doesCompile = false
answer.lineNumber = 5
context = """
Поскольку `s.as_bytes()` производит неизменяемую ссылку на `s`, изменять `s` (через `push_str`) внутри цикла `for` небезопасно.
"""
