[[questions]]
id = "8c9f9173-c5ba-4914-9cfa-e3432f8414e1"
type = "MultipleChoice"
prompt.prompt = """
Какое из перечисленных НЕ является допустимым способом исправить проблему возврата ссылки на стек из функции?
"""
answer.answer = "Продлить время жизни кадра стека"
prompt.distractors = ["Использовать указатель со счетчиком ссылок", "Принять владение возвращаемым значением", "Ожидать изменяемый слот от вызывающей стороны"]
context = """
Время жизни кадра стека нельзя продлить, поэтому это недопустимое решение.
"""

[[questions]]
id = "e6bc84ef-069c-4d1d-99ec-69b13492569c"
type = "MultipleChoice"
prompt.prompt = """
Предположим, программист попытался написать следующую функцию:

```
/// Возвращает имя человека с добавленным титулом "Ph.D."
fn award_phd(name: &String) -> String {
    let mut name = *name;
    name.push_str(", Ph.D.");
    name
}
```

Компилятор Rust отвергает его код со следующей ошибкой:

```text
error[E0507]: cannot move out of `*name` which is behind a shared reference
 --> test.rs:3:20
  |
3 |     let mut name = *name;
  |                    ^^^^^
  |                    |
  |                    move occurs because `*name` has type `String`, which does not implement the `Copy` типаж
  |                    help: consider borrowing here: `&*name`
```

Учитывая заявленную цель функции, какое из следующих изменений будет наиболее идиоматичным исправлением программы? 
Отличия от исходной функции выделены.
"""
answer.answer = """
```
fn award_phd(name: &String) -> String {
    let mut name = `[name.clone()]`;
    name.push_str(", Ph.D.");
    name
}
```
"""
prompt.distractors = [
"""
```
fn award_phd(name: &String) -> String {
    let mut name = `[&*name]`;
    name.push_str(", Ph.D.");
    name
}
```
""",
"""
```
fn award_phd(`[mut name: String]`) -> String {
    name.push_str(", Ph.D.");
    name
}
```
""",
"""
```
fn award_phd(`[name: &mut String]`) {
    name.push_str(", Ph.D.");
}
```
"""
]
context = """
Функция не предназначена для изменения исходного имени, поэтому изменение типа `name` на `&mut String` или `String` было бы неуместным. Предложение компилятора использовать `&*name` недостаточно — приемлемым решением является клонирование данных через `name.clone()` и изменение локальной копии.
"""

[[questions]]
id = "8020e4a2-f0b4-4eae-90ac-a87712d9d00b"
type = "MultipleChoice"
prompt.prompt = """
Предположим, программист попытался написать следующую функцию:

```
/// Округляет все числа с плавающей точкой в векторе до ближайшего целого, на месте
fn round_in_place(v: &Vec<f32>) {
    for n in v {
        *n = n.round();
    }
}
```

Компилятор Rust отвергает его код со следующей ошибкой:

```text
error[E0594]: cannot assign to `*n`, which is behind a `&` reference
 --> test.rs:4:9
  |
3 |     for n in v {
  |              - this iterator yields `&` references
4 |         *n = n.round();
  |         ^^^^^^^^^^^^^^ `n` is a `&` reference, so the data it refers to cannot be written
```

Учитывая заявленную цель функции, какое из следующих изменений будет наиболее идиоматичным исправлением программы? 
Отличия от исходной функции выделены.
"""
answer.answer = """
```
fn round_in_place(v: `[&mut Vec<f32>]`) {
    for n in v {
        *n = n.round();
    }
}
```
"""
prompt.distractors = [
"""
```
fn round_in_place(v: &Vec<f32>) `[-> Vec<f32>]` {
    `[let mut v2 = Vec::new();]`
    for n in v {
        `[v2.push(n.round());]`
    }
    `[v2]`
}
```
""",
"""
```
fn round_in_place(`[mut v: Vec<f32>]`) {
    for n in v {
        *n = n.round();
    }    
}
```
""",
"""
```
fn round_in_place(v: &Vec<f32>) {
    for `[mut n]` in `[&mut v.clone()]` {
        n = n.round();
    }    
}
```
""",
]
context = """
Поскольку эта функция должна округлять вектор на месте, было бы неидиоматично возвращать новую копию того же вектора (`-> Vec<f32>`) или потреблять владение вектором (`mut v: Vec<f32>`). Наилучшим решением является изменение сигнатуры типа с `&Vec<f32>` на `&mut Vec<f32>`.
"""