[[questions]]
id = "cbe8ef63-4f7e-45fd-b11f-e6eba40587b0"
type = "MultipleChoice"
prompt.prompt = """
Что лучше всего объясняет, почему `i32` можно скопировать без перемещения, а `String` — нет?
"""
answer.answer = "`String` владеет данными в куче, а `i32` — нет"
prompt.distractors = [
    "`i32` меньше по размеру в памяти, чем `String`",
    "`i32` — примитивный тип в Rust, а `String` — нет",
    "`String` может размещаться в куче, а `i32` может размещаться только в стеке"
]
context = """
Если бы `String` можно было скопировать без перемещения, то две переменные могли бы считать, что владеют одной и той же строкой, что привело бы к двойному освобождению.
"""

[[questions]]
id = "512e1ec0-cd7b-4a90-949b-d7b08b4009a8"
type = "MultipleChoice"
prompt.prompt = """
Следующий фрагмент кода не компилируется:

```rust
let s = String::from("Hello world");
let s_ref = &s;
let s2 = *s_ref;
println!("{s2}");
```

Что лучше всего описывает неопределённое поведение, которое могло бы произойти, если бы эта программа была разрешена к выполнению?
"""
answer.answer = "Строка освобождается дважды в конце программы"
prompt.distractors = [
  "Чтение `s2` в `println` является использованием освобождённой памяти",
  "Разыменование `*s_ref` является использованием освобождённой памяти",
  "В этой программе нет неопределённого поведения"
]
context = """
`println` технически безопасен, поскольку строка не будет деаллокирована до конца текущей области видимости. Но затем возникает неопределённое поведение, когда строка освобождается дважды от имени `s` и `s2`.
"""

[[questions]]
id = "1e31e163-5bd4-4385-b222-33c19058bf6a"
type = "MultipleChoice"
prompt.prompt = """
Следующая программа не компилируется:

```rust
fn copy_to_prev(v: &mut Vec<i32>, i: usize) {
  let n = &mut v[i];
  *n = v[i - 1];
}
fn main() {
  let mut v = vec![1, 2, 3];
  copy_to_prev(&mut v, 1);
}
```

Что лучше всего описывает неопределённое поведение, которое могло бы произойти, если бы эта программа была разрешена к выполнению?
"""
answer.answer = "В этой программе нет неопределённого поведения"
prompt.distractors = [
  "Присваивание `*n` является использованием освобождённой памяти",
  "Заимствование `&mut v[i]` создаёт указатель на освобождённую память",
  "Чтение `v[i - 1]` является использованием освобождённой памяти"
]
context = """
Эта программа безопасна. Неопределённое поведение не могло бы произойти при её выполнении. (Если `i` выходит за границы `v`, то Rust вызовет панику во время выполнения, а не приведёт к неопределённому поведению.)

Проблема в том, что Rust не знает наверняка, что `v[i]` и `v[i - 1]` ссылаются на разные элементы.
"""

[[questions]]
id = "4df75888-2cd5-4259-8629-46a307429fd0"
type = "MultipleChoice"
prompt.prompt = """
Рассмотрим эту функцию, которая является упрощённым вариантом функции из предыдущего теста:

```
/// Добавляет "Ph.D." к имени человека
fn award_phd(name: &String) {
    let mut name = *name;
    name.push_str(", Ph.D.");
}
```

Компилятор Rust отклоняет эту функцию со следующей ошибкой:

```text
error[E0507]: cannot move out of `*name` which is behind a shared reference
 --> test.rs:3:20
  |
3 |     let mut name = *name;
  |                    ^^^^^
  |                    |
  |                    move occurs because `*name` has type `String`, which does not implement the `Copy` типаж
  |                    help: consider borrowing here: `&*name`
```

Предположим, что компилятор НЕ отклонил эту функцию. Выберите каждую (если есть) из следующих программ, которые потенциально могут вызвать неопределённое поведение при выполнении. Если ни одна из этих программ не может вызвать неопределённое поведение, то отметьте "Ни одна из этих программ".
"""
answer.answer = [
"""
```
let name = String::from("Ferris");
award_phd(&name);
```
""",
"""
```
let name = String::from("Ferris");
award_phd(&name);
println!("{}", name);
```
""",
"""
```
let name = String::from("Ferris");
let name_ref = &name;
award_phd(&name);
println!("{}", name_ref);
```
""",

]
prompt.distractors = [
  "Ни одна из этих программ"
]
context = """
Инструкция `let mut name = *name` заставляет `name` взять владение входной строкой.
Однако вызывающая сторона также по-прежнему сохраняет владение строкой. Поэтому после завершения `award_phd`
строка освобождается. Следовательно, каждая из вышеперечисленных программ имеет неопределённое поведение, 
потому что `name` в конечном итоге будет освобождена во второй раз. Не имеет значения, читается ли `name`
или ссылка на `name` после вызова `award_phd`.
"""

[[questions]]
id = "1f48fda5-afc6-440b-a9aa-53dc8d54efaa"
type = "Tracing"
prompt.program = """
fn main() {
    let mut point = [0, 1];
    let mut x = point[0];
    let y = &mut point[1];
    x += 1;
    *y += 1;
    println!("{} {}", point[0], point[1]);
}
"""
answer.doesCompile = true
answer.stdout = "0 2"
context = """
Эта программа компилируется, поскольку привязка `x` копирует `point[0]`, позволяя `y` изменяемо заимствовать `point[1]`.
Изменение `x += 1` не влияет на `point`, в то время как изменение `*y += 1` влияет, поэтому окончательный результат — `0 2`.
"""