[[questions]]
id = "889ca9ac-0f4b-4abf-82c4-be9cd4d4f7ad"
type = "MultipleChoice"
prompt.prompt = "Что из перечисленного НЕ является видом неопределённого поведения?"
answer.answer = "Наличие указателя на освобождённую память в кадре стека"
prompt.distractors = [
  "Использование указателя, который указывает на освобождённую память",
  "Освобождение одной и той же памяти второй раз",
  "Использование небулевого значения в качестве условия `if`"
]
context = """
Наличие указателя на освобождённую память в кадре стека может быть абсолютно безопасным.
Главное — не *использовать* этот указатель повторно, например, не читать его или не освобождать.
"""

[[questions]]
id = "94425a4e-043e-47f8-9fba-c5b09fb60aa3"
type = "Tracing"
prompt.program = """
fn add_suffix(mut s: String) -> String {
  s.push_str(" world");
  s
}

fn main() {
  let s = String::from("hello");
  let s2 = add_suffix(s);
  println!("{}", s2);
}
"""
answer.doesCompile = true
answer.stdout = "hello world"
context = """
Эта программа корректна, потому что `s` не используется после перемещения её в `add_suffix`.
"""

[[questions]]
id = "c00e3638-861b-4f9e-a55c-bfb67af79280"
type = "Tracing"
prompt.program = """
fn main() {
  let s = String::from("hello");
  let s2;
  let b = false;
  if b {
    s2 = s;
  }
  println!("{}", s);
}
"""
answer.doesCompile = false
answer.lineNumber = 8
context = """
Поскольку `s` может быть перемещено внутри блока if, использование её на строке 8 недопустимо.
Хотя блок if в этой программе никогда не выполнится, потому что `b` всегда `false`,
Rust в общем случае не пытается определить, будут ли блоки if выполнены или нет. Rust просто
предполагает, что они *могут* быть выполнены, и поэтому `s` *может* быть перемещена.
"""

[[questions]]
id = "f7d67c11-60bb-4d92-8cc2-8ce82cf4c974"
type = "MultipleChoice"
prompt.prompt = """
Предположим, у нас есть функция, которая перемещает коробку, вот так:
```
fn move_a_box(b: Box<i32>) {
  // Это пространство оставлено намеренно пустым
}
```

Ниже приведены четыре фрагмента кода, которые компилятор Rust отвергает. 
Представьте, что Rust вместо этого разрешит компиляцию и выполнение этих фрагментов. 
Выберите каждый фрагмент, который вызвал бы неопределённое поведение, или выберите 
«Ни один из этих фрагментов», если ни один из них не вызвал бы неопределённого поведения.
"""
answer.answer = [
"""
```
let b = Box::new(0);
let b2 = b;
move_a_box(b);
```
""",
"""
```
let b = Box::new(0);
move_a_box(b);
println!("{}", b);
```
""",
"""
```
let b = Box::new(0);
move_a_box(b);
let b2 = b;
```
"""
]
prompt.distractors = [
"""
```
let b = Box::new(0);
let b2 = b;
println!("{}", b);
move_a_box(b2);
```
""",
"Ни один из этих фрагментов"
]
context = """
Ключевая идея в том, что когда коробка передаётся в `move_a_box`, её память освобождается после завершения `move_a_box`.
Следовательно:
* Чтение `b` через `println` после `move_a_box` вызывает неопределённое поведение, так как читается освобождённая память.
* Предоставление `b` второго владельца вызывает неопределённое поведение, так как это привело бы к повторному освобождению коробки от имени `b2`. Неважно, происходит ли привязка `let b2 = b` до или после `move_a_box`.

Однако выполнение `let b2 = b`, а затем `println` не вызывает неопределённого поведения. Хотя `b` перемещена, её данные не освобождаются, пока `move_a_box` не будет вызвана в конце. Поэтому эта программа технически безопасна, хотя Rust всё равно отвергает её.
"""