[[questions]]
id = "1ec0098c-c5dc-46de-a889-b6659c0af757"
type = "MultipleChoice"
prompt.prompt = """
Предположим, вы пишете функцию со следующей спецификацией:

> `round_all` принимает на вход список чисел с плавающей точкой и округляет каждое число на месте до ближайшего целого.

Какой из следующих вариантов наиболее подходящая сигнатура типа для функции, реализующей эту спецификацию?
"""
answer.answer = """
```
fn round_all(v: &mut Vec<f32>);
```
"""
prompt.distractors = [
"""
```
fn round_all(v: &Vec<f32>) -> Vec<f32>;
```
""",
"""
```
fn round_all(v: Vec<f32>);
```
""",
"""
```
fn round_all(v: &Vec<f32>);
```
"""
]
context = """
Спецификация требует изменения входных данных на месте, поэтому наиболее подходящая сигнатура типа принимает изменяемую ссылку на входные данные.
Неизменяемая ссылка или владеющий вектор не подходят для этой спецификации.
"""

[[questions]]
id = "f8ca5ab2-0e5d-4c0d-bca2-99e6763ba9c5"
type = "MultipleChoice"
prompt.prompt = """
Предположим, вы пишете функцию со следующей спецификацией:

> `find_contains` принимает на вход коллекцию строк и целевую подстроку.
> Она возвращает список всех строк в коллекции, которые содержат целевую подстроку.

Какой из следующих вариантов наиболее подходящая сигнатура типа для функции, реализующей эту спецификацию?
"""
answer.answer = """
```
fn find_contains(haystack: &[String], needle: &str) -> Vec<&String>;
```
"""
prompt.distractors = [
"""
```
fn find_contains(haystack: &Vec<String>, needle: String) -> Vec<String>;
```
""",
"""
```
fn find_contains(haystack: &[String], needle: &str) -> Vec<String>;
```
""",
"""
```
fn find_contains(haystack: &Vec<String>, needle: &str) -> &[String];
```
"""
]
context = """
Для `haystack` тип среза `&[String]` может принимать больше входных данных, чем `&Vec<String>`, поэтому он предпочтительнее.
Для `needle` целевая подстрока не обязательно должна быть выделена в куче, поэтому `&str` предпочтительнее `String`.
Для возвращаемого типа `Vec<String>` нежелателен, потому что он потребовал бы клонирования входных строк.
`&[String]` нежелателен, потому что он может возвращать только непрерывную подпоследовательность входных данных.
`Vec<&String>` наиболее предпочтителен, потому что он несет только стоимость выделения вектора, а не самих строк.
"""

[[questions]]
id = "868a4edf-16f0-4191-8aed-835c812b8b25"
type = "MultipleChoice"
prompt.prompt = """
Rust обычно запрещает несколько изменяемых доступов к одному и тому же массиву, даже когда эти доступы не пересекаются.
Например, эта функция не компилируется:

```
fn main() {
  let mut v = vec![0, 1, 2, 3];
  let (r0, r1) = (&mut v[0..2], &mut v[2..4]);
  r0[0] += 1;
  r1[0] += 1;  
}
```

Однако в стандартной библиотеке Rust есть функция `slice::split_at_mut`, которая разрешает эту функциональность:

```
fn main() {
  let mut v = vec![0, 1, 2, 3];
  let (r0, r1) = v.split_at_mut(2);
  r0[0] += 1;
  r1[0] += 1;  
}
```

Какой из следующих вариантов лучше всего описывает, как возможно реализовать `split_at_mut`?
"""
answer.answer = "`split_at_mut` использует небезопасный код для обхода проверки заимствований с помощью сырых указателей"
prompt.distractors = [
"`split_at_mut` — это специальный примитив компилятора, который нельзя реализовать внутри языка",
"`split_at_mut` использует небезопасный код для отключения проверки заимствований при проверке безопасности изменяемых ссылок",
"`split_at_mut` вызывает C-библиотеку, которую Rust не может проанализировать"
]
context = """
Как обсуждалось в [Главе 4.3 "Исправление безопасной программы: изменение разных элементов массива"](ch04-03-fixing-ownership-errors.html#fixing-a-safe-program-mutating-different-array-elements), такие функции, как `split_at_mut`, реализуются с помощью возможности `unsafe`.
Эта возможность не полностью отключает проверку заимствований, а скорее позволяет использовать конкретные небезопасные возможности, такие как сырые указатели.
"""

[[questions]]
id = "ba32e57a-e5f2-42e4-8cfd-eb265990c690"
type = "MultipleChoice"
prompt.prompt = """
Рассмотрим разрешения в следующей программе:

```aquascope,permissions,boundaries,stepper
#fn main() {
let s = String::new();
let s_ref = &s;`(focus,paths:*s_ref)`
#println!("{s_ref}");
#}
```

Какой из следующих вариантов лучше всего объясняет, почему `*s_ref` не имеет разрешения @Perm{own} (владение)?
"""
answer.answer = "Владение разрешает перемещение, а перемещение из ссылки может привести к двойному освобождению"
prompt.distractors = [
  "Владение разрешает заимствование, и повторное заимствование `*s_ref` может привести к двойному освобождению",
  "Владение разрешает изменение, и изменение `*s_ref` может привести к использованию после освобождения",
  "Владение разрешает чтение, и чтение `*s_ref` может привести к использованию после освобождения"
]
context = """
Разрешение @Perm{own} представляет владение объектом. Объектом может быть только один владелец, поэтому важно,
чтобы ссылки не могли передавать владение некопируемыми типами, такими как `String`. Если две переменные считали бы,
что владеют одной и той же строкой, то обе попытались бы её освободить, вызвав двойное освобождение.
"""

[[questions]]
id = "3a5f5de5-23a9-49fb-bdb4-acc9c3fbb4a6"
type = "MultipleChoice"
prompt.prompt = """
Рассмотрим набор программ на Rust, которые не содержат `небезопасного` кода.
Выберите все верные утверждения из следующих о типах программ, которые принимает и отклоняет проверка заимствований:
"""
answer.answer = [
  "Проверка заимствований всегда отклоняет программы с неопределённым поведением",
  "Проверка заимствований иногда отклоняет программы без неопределённого поведения",
]
prompt.distractors = [
  "Проверка заимствований всегда принимает программы без неопределённого поведения",  
  "Проверка заимствований иногда принимает программы с неопределённым поведением"
]
context = """
Проверка заимствований всегда отклоняет программы с неопределённым поведением, но может иногда отклонять программы без неопределённого поведения (т.е. совершенно безопасные).
С технической точки зрения, проверка заимствований — это звуковой и неполный анализ.
"""

[[questions]]
id = "208e0e38-a706-4d96-9809-f0e12f574136"
type = "MultipleChoice"
prompt.prompt = """
Функция `extract` отклонена проверкой заимствований:

```rust
fn extract(b: &Box<i32>) -> i32 {
    let b2: Box<i32> = *b;
    *b2
}
```

Представьте, что проверка заимствований не отклонила бы эту функцию.
Определите, существует ли такой вход, при котором выполнение этой функции вызвало бы неопределённое поведение.
"""
answer.answer = "Эта функция МОЖЕТ вызвать неопределённое поведение"
prompt.distractors = ["Эта функция НЕ МОЖЕТ вызвать неопределённое поведение"]
context = """
Эта функция вызвала бы двойное освобождение при любом входе.
"""

[[questions]]
id = "dcfd54f8-7fe6-4483-aefd-ea95ba5b5eb0"
type = "MultipleChoice"
prompt.prompt = """
Функция `transfer_string` отклонена проверкой заимствований:

```rust
fn get_first(strs: &mut (String, String)) -> &mut String {
    &mut strs.0
}

fn get_second(strs: &mut (String, String)) -> &mut String {
    &mut strs.1
}

fn transfer_string(strs: &mut (String, String)) {
    let fst = get_first(strs);
    let snd = get_second(strs);
    fst.push_str(snd);
    snd.clear();
}
```

Представьте, что проверка заимствований не отклонила бы эту функцию.
Определите, существует ли такой вход, при котором выполнение этой функции вызвало бы неопределённое поведение.
"""
answer.answer = "Эта функция НЕ МОЖЕТ вызвать неопределённое поведение"
prompt.distractors = ["Эта функция МОЖЕТ вызвать неопределённое поведение"]
context = """
Проверка заимствований отклоняет эту функцию, потому что она предполагает, что `get_first` и `get_second` могли бы возвращать изменяемую ссылку на любой компонент кортежа, и поэтому `fst` и `snd` могли бы возможно указывать на одно и то же значение. Но они всегда различны в этой программе, поэтому эта функция на самом деле безопасна.
"""