[[questions]]
id = "5080616f-6f4c-43f7-aa3a-8b23f2798937"
type = "Tracing"
prompt.program = """
fn incr(n: &mut i32) {
  *n += 1;
}

fn main() {
  let mut n = 1;
  incr(&n);
  println!("{n}");
}
"""
answer.doesCompile = false
answer.lineNumber = 7
context = """
Хотя `n` помечен как `mut`, ссылка на `n` также должна быть помечена как `mut`. 
Поэтому корректная версия этой программы должна использовать `incr(&mut n)`.
"""

[[questions]]
id = "e9846c5d-1254-4420-9986-dae4af86b9af"
type = "Tracing"
prompt.program = """
fn main() {
  let mut s = String::from("hello");
  let s2 = &s;
  let s3 = &mut s;
  s3.push_str(" world");
  println!("{s2}");
}
"""
answer.doesCompile = false
answer.lineNumber = 6
context = """
Незаконно использовать изменяемую ссылку на значение (`s3`), пока существует неизменяемая ссылка (`s2`).
"""

[[questions]]
id = "80f6bcd6-b74a-4da3-a014-d423c82ce405"
type = "MultipleChoice"
prompt.prompt = """
Рассмотрим эту функцию на Rust, которая добавляет число в конец вектора, а затем удаляет и возвращает число из начала вектора:

```
fn give_and_take(v: &Vec<i32>, n: i32) -> i32 {
    v.push(n);
    v.remove(0)
}
```

Обычно, если вы попытаетесь скомпилировать эту функцию, компилятор вернёт следующую ошибку:

```text
error[E0596]: cannot borrow `*v` as mutable, as it is behind a `&` reference
 --> test.rs:2:5
  |
1 | fn give_and_take(v: &Vec<i32>, n: i32) -> i32 {
  |                     --------- help: consider changing this to be a mutable reference: `&mut Vec<i32>`
2 |     v.push(n);
  |     ^^^^^^^^^ `v` is a `&` reference, so the data it refers to cannot be borrowed as mutable
```

Предположим, что компилятор НЕ отклонил эту функцию. Выберите каждую (если есть) из следующих программ, которые потенциально могут вызвать неопределённое поведение при выполнении. Если ни одна из этих программ не может вызвать неопределённое поведение, 
то отметьте "Ни одна из этих программ" .
"""
answer.answer = [
"""
```
let v = vec![1, 2, 3];
let n = &v[0];
give_and_take(&v, 4);
println!("{}", n);
```
""",
]
prompt.distractors = [
"""
```
let v = vec![1, 2, 3];
let v2 = &v;
give_and_take(&v, 4);
println!("{}", v2[0]);
```
""",
"""
```
let v = vec![1, 2, 3];
let n = &v[0];
let k = give_and_take(&v, 4);
println!("{}", k);
```
""",
"Ни одна из этих программ"
]
context = """
Как мы видели ранее в разделе, `v.push(n)` может привести к тому, что `v` перераспределит своё внутреннее содержимое, инвалидируя любые ссылки на элементы `v` в куче.
Поэтому вызов `give_and_take(&v, 4)` приведёт к тому, что ранее созданные ссылки на элементы будут указывать на недействительную память. Две программы, которые создают привязку `let n = &v[0]`
перед `give_and_take`, являются кандидатами на неопределённое поведение. `let v2 = &v` не является кандидатом, потому что ссылка на контейнер `v` фактически не инвалидируется 
при изменении `v`.

Программа, которая выполняет `println!("{}", n)`, вызовет неопределённое поведение, читая недействительную память. Программа, которая выполняет `println!("{}", k)`, не вызовет неопределённое
поведение, потому что она не использует инвалидированную ссылку.
"""