[[questions]]
id = "0b8dbb4f-7c56-4b6e-8358-95c7b46f90c3"
type = "ShortAnswer"
prompt.prompt = """
Рассмотрим следующую программу, показывающую состояние памяти после последней строки:
```aquascope,interpreter
#fn main() {
let x = Box::new(0);
let y = Box::new(&x);`[]`
#}
```

Если вы хотите скопировать число `0` через `y`, сколько раз вам нужно использовать разыменование? 
Запишите ответ в виде цифры. Например, если правильное выражение — `*y`, то ответ — 1.
"""
answer.answer = "3"
context = """
`***y` — правильное выражение. `y` имеет тип `Box<&Box<i32>>`. Это указатель на кучу на ссылку на стек на указатель на кучу. 
Следовательно, `y` нужно разыменовать три раза, по одному для каждого уровня косвенности.
"""

[[questions]]
id = "7cf19153-3647-4afc-953a-f9392ddb96fb"
type = "MultipleChoice"
prompt.prompt = """
Рассмотрим следующую программу, показывающую состояние памяти после последней строки:
 
```aquascope,interpreter
fn get_first(vr: &Vec<i32>) -> i32 {
  vr[0]
}

fn main() {
  let mut v = vec![0, 1, 2];
  let n = get_first(&v);
  println!("{} {}", n, v[1]);`[]` 
}
```

Какой из следующих вариантов лучше всего объясняет, почему `v` не освобождается после вызова `get_first`?
"""
answer.answer = "`vr` является ссылкой, которая не владеет вектором, на который указывает"
prompt.distractors = [
  "`vr` не изменяется внутри `get_first`",
  "`get_first` возвращает значение типа `i32`, а не сам вектор",
  "`v` используется после вызова `get_first` в `println`"
]
context = """
Ссылки — это невладеющие указатели. Поэтому передача `&v` в `get_first` не передает владение `v` в `get_first`,
и впоследствии `v` не освобождается после завершения `get_first`.
"""