[[questions]]
id = "97781ca8-ad58-449c-9769-e20b9d2e42a6"
type = "MultipleChoice"
prompt.prompt = """
Предположим, у вас есть переменная `v` типа `&mut Vec<i32>`, и вы хотите вызвать метод `len` со следующей сигнатурой:

```
impl Vec<i32> {
  fn len(&self) -> usize {
    /* ... */
  }
}
```

Если вы попытаетесь скомпилировать выражение `v.len()`, какое из следующих утверждений лучше всего описывает, что происходит?
"""
answer.answer = "Это компилируется, потому что ссылка `&mut` неявно повторно заимствуется как ссылка `&`"
prompt.distractors = [
  "Не компилируется, потому что `&mut Vec<i32>` не того же типа, что `&Vec<i32>`",
  "Не компилируется, `v` не разыменовывается явно",
  "Компилируется, потому что `&self` может принимать любой вид ссылки"
]
context = """
Выражение `v.len()` раскрывается в `Vec::len(&*v)`, что является допустимым повторным заимствованием `v`, поэтому это выражение компилируется.
Однако нельзя передать `v` напрямую в `Vec::len`, поскольку `&self` специально относится к неизменяемым ссылкам.
"""

[[questions]]
id = "35a75881-eb08-486c-92b3-413ab512138a"
type = "MultipleChoice"
prompt.prompt = """
Рассмотрим эти два метода, которые увеличивают поле структуры. Какой стиль будет более идиоматичным для Rust?

```
struct Point(i32, i32);
impl Point {
  fn incr_v1(mut self)  { self.0 += 1; }
  fn incr_v2(&mut self) { self.0 += 1; }
}
```
"""
answer.answer = "`incr_v2`"
prompt.distractors = [
  "`incr_v1`",
  "Оба идиоматичны",
  "Ни один не идиоматичен"
]
prompt.answerIndex = 1
context = """
Метод `incr_v1` не идиоматичен, потому что он потребляет владение `Point`. Это означает, что после вызова `p.incr_v1()`, `p` станет непригодным для использования, что, вероятно, не предполагается для этого метода.
"""

[[questions]]
id = "03a0a1ec-8ce6-40f2-b8b7-6dd5402aeb7d"
type = "Tracing"
prompt.program = """
struct Point(i32, i32);
impl Point {
  fn incr_x(&mut self) {
    self.0 += 1;
  }
}

fn main() {
  let mut p = Point(0, 0);
  p.incr_x();
  println!("{}", p.0);
}
"""
answer.doesCompile = true
answer.stdout = "1"
context = """ 
Помните, что `.0` допустим для кортежных структур, таких как `Point`.
"""

[[questions]]
id = "be7be598-8a31-4c1a-9171-4ff90f512430"
type = "Tracing"
prompt.program = """
struct Point {
  x: i32,
  y: i32
}

impl Point {
  fn get_x(&mut self) -> &mut i32 {
    &mut self.x
  }
}

fn main() {
  let mut p = Point { x: 1, y: 2 };
  let x = p.get_x();
  *x += 1;
  println!("{} {}", *x, p.y);
}
"""
answer.doesCompile = false
answer.lineNumber = 16
context = """ 
Поскольку `get_x` изменяемо заимствует весь `p`, программа не может использовать `p` каким-либо образом, пока `x` больше не используется. 
Поэтому чтение `x` и `p.y` в одной строке является ошибкой владения.
"""