[[questions]]
id = "f0ec64fa-262f-4819-8379-acad7aaf8be2"
type = "Tracing"
prompt.program = """
#[derive(Debug)]
struct Rectangle {
  width: u32,
  height: u32,
}

fn main() {
  let rect1 = Rectangle {
    width: 30,
    height: 50,
  };

  let a = area(rect1);
  println!("{} * {} = {}", rect1.width, rect1.height, a);
}

fn area(rectangle: Rectangle) -> u32 {
  rectangle.width * rectangle.height
}
"""
answer.doesCompile = false
answer.lineNumber = 14
context = """ 
Функция `area` принимает владение своим аргументом `rectangle`. Поэтому вызов `area(rect1)` перемещает `rect1`, что означает, что его нельзя использовать в следующей строке.
"""

[[questions]]
id = "9ce4156e-4112-4101-a2c7-51758ceca639"
type = "MultipleChoice"
prompt.prompt = "Какое утверждение лучше всего описывает разницу между типажами `Display` и `Debug`?"
answer.answer = "`Display` предназначен для представления значений конечному пользователю, а `Debug` — для внутреннего использования разработчиками"
prompt.distractors = [
  "`Display` предназначен для печати значений в консоль, а `Debug` — для просмотра значений в отладчике",
  "`Display` нельзя реализовать для структур, а `Debug` можно реализовать для структур",
  "Разницы нет, `Display` и `Debug` — это псевдонимы для одного и того же типажа."
]