[[questions]]
id = "6e5e193e-579d-4a46-aae4-d35336b77b68"
type = "MultipleChoice"
prompt.prompt = """
**Программа 1:**

```ide
/// Создает строку-разделитель для строк текста,
/// возвращая значение по умолчанию, если предоставленная строка пуста
fn make_separator(user_str: &str) -> &str {
    if user_str == "" {
        let default = "=".repeat(10);
        &default
    } else {
        user_str
    }
}
```

Если бы вы попытались скомпилировать эту функцию, какое из следующих описаний наилучшим образом соответствует ошибке компилятора, которую вы получите?
"""
answer.answer = "нельзя вернуть ссылку на локальную переменную `default`"
prompt.distractors = [
  "`user_str` не живет достаточно долго",
  "функция `make_separator` не может вернуть ссылку типа `&str`",
  "функция `make_separator` не может вернуть две разные ссылки"
]
context = """
Поскольку `default` находится в стеке внутри `make_separator`, она будет освобождена после завершения вызова `make_separator`.
Это оставляет `&default` указывающим на освобожденную память. Поэтому Rust жалуется, что нельзя вернуть ссылку на локальную переменную.
"""

[[questions]]
id = "44a2eb01-b49a-497b-a9d2-207814d1db1e"
type = "MultipleChoice"
prompt.prompt = """
**Программа 1:**

```ide
/// Создает строку-разделитель для строк текста,
/// возвращая значение по умолчанию, если предоставленная строка пуста
fn make_separator(user_str: &str) -> &str {
    if user_str == "" {
        let default = "=".repeat(10);
        &default
    } else {
        user_str
    }
}
```

Обычно, если вы попытаетесь скомпилировать эту функцию, компилятор вернет следующую ошибку:

```text
error[E0515]: cannot return reference to local variable `default`
 --> test.rs:6:9
  |
6 |         &default
  |         ^^^^^^^^ returns a reference to data owned by the current function
```

Предположим, что компилятор НЕ отклонил эту функцию. Какие (если такие есть) из следующих программ
(1) пройдут компиляцию и (2) потенциально вызовут неопределенное поведение при выполнении?
Отметьте каждую программу, удовлетворяющую обоим критериям, ИЛИ отметьте "Ни одна из этих программ", если ни одна не удовлетворяет.
"""
answer.answer = ["""
```
let s = make_separator("");
println!("{s}");
```
"""]
prompt.distractors = [
"""
```
println!("{}", make_separator("Hello world!"));
```
""",
"Ни одна из этих программ",
]
context = """
Вызывающий должен передать пустую строку, чтобы активировать проблематичное условие if. Это возвращает висячий указатель.
"""

[[questions]]
id = "815ae4cd-0f23-4da5-9dc2-0e81c664cc28"
type = "MultipleChoice"
prompt.prompt = """
**Программа 1:**

```ide
/// Создает строку-разделитель для строк текста,
/// возвращая значение по умолчанию, если предоставленная строка пуста
fn make_separator(user_str: &str) -> &str {
    if user_str == "" {
        let default = "=".repeat(10);
        &default
    } else {
        user_str
    }
}
```

Какое из следующих исправлений (подсвечено желтым) наилучшим образом удовлетворяет трем критериям:
1. Исправленная функция проходит компиляцию Rust,
2. Исправленная функция сохраняет намерение исходного кода и
3. Исправленная функция не вносит ненужных неэффективностей
"""
answer.answer = """
```ide
fn make_separator(user_str: &str) -> `[String]` {
    if user_str == "" {
        let default = "=".repeat(10);
        `[default]`
    } else {
        `[user_str.to_string()]`        
    }
}
```
"""
prompt.distractors = [
"""
```ide
fn make_separator(user_str: &str) -> &str {
    if user_str == "" {
        let default = "=".repeat(10);
        &default
    } else {
        `[&user_str]`
    }
}
```
""",
"""
```ide
fn make_separator(user_str: `[String]`) -> `[String]` {
    if user_str == "" {
        let default = "=".repeat(10);
        `[default]`
    } else {
        user_str
    }
}
```
""",
]
context = """
Нет допустимого способа вернуть указатель на переменную, размещенную в стеке. Поэтому простое решение — изменить тип возвращаемого значения на `String`
и скопировать входной `user_str` во владеющую строку. Однако требование, чтобы `user_str` был `String`, снижает гибкость API, например.
вызывающий не сможет вызвать `make_separator` для подстроки большей строки. Это также потребует от вызывающих выделения строк в куче, например.
они не смогут использовать строковый литерал вроде `make_separator("Rust")`.

Наиболее идиоматичное решение этой проблемы использует конструкцию, которую вы еще не видели: [`Cow`](https://doc.rust-lang.org/std/borrow/enum.Cow.html).
Умный указатель "клонировать-при-записи" позволит этой функции возвращать *либо* владеющую строку *либо* ссылку на строку без ошибки типа.
"""

[[questions]]
id = "1f4e5c06-ecdf-481d-9cae-8a25dafe9cfd"
type = "MultipleChoice"
prompt.prompt = """
**Программа 2:**

```ide
/// Извлекает строку из option, если она существует,
/// возвращая значение по умолчанию в противном случае
fn get_or_default(arg: &Option<String>) -> String {
    if arg.is_none() {
        return String::new();
    }
    let s = arg.unwrap();
    s.clone()
}
```

Если бы вы попытались скомпилировать эту функцию, какое из следующих описаний наилучшим образом соответствует ошибке компилятора, которую вы получите?
"""
answer.answer = "нельзя переместить из `arg` в `arg.unwrap()`"
prompt.distractors = [
  "нельзя вызвать `arg.is_none()` без разыменования `arg`",
  "`arg` не живет достаточно долго",
  "нельзя вернуть `s.clone()`, который не живет достаточно долго"
]
context = """
Функция `Option::unwrap` ожидает `self`, то есть ожидает владение `arg`. Однако `arg` — это неизменяемая ссылка на option,
поэтому она не может предоставить владение option. Поэтому компилятор жалуется, что мы 
не можем переместиться из `arg` через `unwrap`.
"""

[[questions]]
id = "989670b2-b038-47c4-9975-a93d6ee193e5"
type = "MultipleChoice"
prompt.prompt = """
**Программа 2:**

```ide
/// Извлекает строку из option, если она существует,
/// возвращая значение по умолчанию в противном случае
fn get_or_default(arg: &Option<String>) -> String {
    if arg.is_none() {
        return String::new();
    }
    let s = arg.unwrap();
    s.clone()
}
```

Обычно, если вы попытаетесь скомпилировать эту функцию, компилятор вернет следующую ошибку:

```text
error[E0507]: cannot move out of `*arg` which is behind a shared reference
   --> test.rs:7:13
    |
7   |     let s = arg.unwrap();
    |             ^^^^--------
    |             |   |
    |             |   `*arg` moved due to this method call
    |             help: consider calling `.as_ref()` or `.as_mut()` to borrow the type's contents
    |             move occurs because `*arg` has type `Option<String>`, which does not implement the `Copy` trait
```

Предположим, что компилятор НЕ отклонил эту функцию. Какие (если такие есть) из следующих программ
(1) пройдут компиляцию и (2) потенциально вызовут неопределенное поведение при выполнении?
Отметьте каждую программу, удовлетворяющую обоим критериям, ИЛИ отметьте "Ни одна из этих программ", если ни одна не удовлетворяет.
"""
answer.answer = [
"""
```
let opt = Some(String::from("Rust"));
get_or_default(&opt);
println!("{:?}", opt);
```
""",
"""
```
let opt = Some(String::from("Rust"));
let s = get_or_default(&opt);
println!("{}", s);
```
""", 
"""
```
let opt = Some(String::from("Rust"));
get_or_default(&opt);
```
""", 
]
prompt.distractors = [
"Ни одна из этих программ",
]
context = """
Все эти программы нарушают безопасность памяти из-за двойного освобождения. Если бы `arg.unwrap()` было разрешено,
то владение строкой `String::from("Rust")` было бы принято `s`. После возврата `get_or_default` строка будет освобождена.
Однако `opt` также считает, что владеет строкой, поэтому 
строка будет освобождена второй раз от имени `opt`.
"""

[[questions]]
id = "3a8d5bb8-a204-43e6-b50a-d17c803dbe37"
type = "MultipleChoice"
prompt.prompt = """
**Программа 2:**

```ide
/// Извлекает строку из option, если она существует,
/// возвращая значение по умолчанию в противном случае
fn get_or_default(arg: &Option<String>) -> String {
    if arg.is_none() {
        return String::new();
    }
    let s = arg.unwrap();
    s.clone()
}
```

Какое из следующих исправлений (подсвечено желтым) наилучшим образом удовлетворяет трем критериям:
1. Исправленная функция проходит компиляцию Rust,
2. Исправленная функция сохраняет намерение исходного кода и
3. Исправленная функция не вносит ненужных неэффективностей
"""
answer.answer = """
```ide
fn get_or_default(arg: &Option<String>) -> String {
    `[match arg {]`
        `[None => String::new(),]`
        `[Some(s) => s.clone()]`
    `[}]`
}
```
"""
prompt.distractors = [
"""
```ide
fn get_or_default(arg: `[&mut Option<String>]`) -> String {
    if arg.is_none() {
        return String::new();
    }
    let s = arg`[.as_mut()]`.unwrap();
    s.clone()
}
```
""",
"""
```ide
fn get_or_default(arg: `[Option<String>]`) -> String {
    if arg.is_none() {
        return String::new();
    }
    let s = arg.unwrap();
    s.clone()
}
```
""",
"""
```ide
fn get_or_default(arg: &Option<`[&str]`>) -> String {
    if arg.is_none() {
        return String::new();
    }
    let s = arg.unwrap();
    `[s.to_string()]`
}
```
""",
]
context = """
Комбинация `is_none` и `unwrap` здесь является антипаттерном Rust, так как `match` объединяет оба функционала и
автоматически занимается проталкиванием ссылки `&Option` внутрь, чтобы произвести `&String`. Поэтому решение с `match`
наиболее идиоматично и проходит компиляцию без изменения предполагаемой сигнатуры типа функции.

Решение изменения `&Option` на `Option` нежелательно, потому что оно требует от вызывающего предоставить владение своим option,
что является гораздо более ограничивающим API.
"""