[[questions]]
id = "5b6e4016-c089-4cb3-96a7-ca9f88694488"
type = "Tracing"
prompt.program = """
enum Location {
  Point(i32),
  Range(i32, i32)
}

fn main() {
  let l: Location = Location::Range(0, 5);
  let n = match l {
    Location::Point(_) => -1,
    Location::Range(_, 5) => 5,
    Location::Range(0, _) => 0,
    _ => -2
  };
  println!("{n}");
}
"""
answer.doesCompile = true
answer.stdout = "5"
context = """ 
Каждый вариант сопоставления проверяется сверху вниз. Оба второго и третьего образца применимы, поэтому используется второй.
"""

[[questions]]
id = "f7c361e0-733a-4d48-9809-736e3c1e2b67"
type = "MultipleChoice"
prompt.prompt = """
Рассмотрим этот метод, реализованный для типа `Option`:

```
impl<T> Option<T> {
  fn unwrap_or(self, other: T) -> T {
    match self {
      Some(t) => t,
      None => other
    }
  }
}
```

Какое предложение лучше всего описывает поведение этой функции?
"""
answer.answer = "Возвращает объект внутри `self`, если он существует, и `other` в противном случае"
prompt.distractors = [
  "Возвращает новую опцию, содержащую объект внутри `self`, если он существует, и `other` в противном случае",
  "Вставляет `other` в `self`, если `self` не содержит значение",
  "Возвращает ссылку на объект внутри `self`, если он существует, и `other` в противном случае"
]
context = """
Эта функция «разворачивает» опцию, потребляя владение ею и извлекая внутреннее значение, но если значение отсутствует, то она возвращается к `other`.
Это реальная функция из стандартной библиотеки!
"""

[[questions]]
id = "1e4f082c-ffa4-4d33-8726-2dbcd72e1aa2"
type = "Tracing"
prompt.program = """
#[derive(Debug)]
enum Either {
  Left(usize),
  Right(String)
}

fn main() {
  let x = Either::Right(String::from("Hello world"));
  let value = match x {
    Either::Left(n) => n,
    Either::Right(s) => s.len()
  };
  println!("{x:?} {value}");
}
"""
answer.doesCompile = false
answer.lineNumber = 13
context = """
Арма сопоставления `Either::Right(s)` перемещает поле `s`, поэтому `x` не может быть использован в `println`.
"""

[[questions]]
id = "6e012d34-5c59-443e-85d9-385f0d7dee13"
type = "MultipleChoice"
prompt.prompt = """
Рассмотрим эти две реализации функции для двойного уменьшения беззнакового числа.

```
fn decr_twice_v1(n: u32) -> Option<u32> {
  match n {
    0 => None,
    1 => None,
    n2 => Some(n2 - 2)
  }
}

fn decr_twice_v2(n: u32) -> Option<u32> {
  if n == 0 {
    None
  } else if n == 1 {
    None
  } else {
    Some(n - 2)
  }
}
```

Функции имеют одинаковое поведение для:
"""
answer.answer = "Всех входных данных"
prompt.distractors = [ "Никаких входных данных", "Некоторые, но не все входные данные" ]
context = """
`match` и `if` здесь выполняют одну и ту же функцию. Сопоставление — это специализированный `if`, который проверяет равенство сопоставляемого объекта.
"""