[[questions]]
id = "770f09d3-110d-4505-b41a-2af422198d59"
type = "Tracing"
prompt.program = """
fn foo(x: &i32) { 
  println!("{x}");
}

fn main() {
  let x = null;
  foo(x);
}
"""
answer.doesCompile = false
answer.lineNumber = 6
context = """ 
Rust не имеет нулевых указателей, поэтому ключевое слово `null` не существует. Для представления возможности объекта быть нулевым следует использовать тип Option.
"""

[[questions]]
id = "6226be11-31c3-4cac-b97c-515514a70af2"
type = "MultipleChoice"
prompt.prompt = """
Рассмотрим два представления типа `Result`, который содержит значение `T`, если вычисление завершилось успешно, или ошибку `E`, если оно завершилось неудачей.

```
struct Result1<T, E> {
  ok: Option<T>,
  err: Option<E>,
}

enum Result2<T, E> {
  Ok(T),
  Err(E)
}
```

Перечисление `Result2` считается более идиоматичным в Rust, чем структура `Result1`. 
Какой из приведённых ниже аргументов **НЕ** является верной причиной?
"""
answer.answer = "Структура содержит типы `Option`, которые предназначены только для обёртывания структур"
prompt.distractors = [
  "Структура использует больше места в памяти во время выполнения, чем перечисление",
  "У структуры могут быть и `ok`, и `err` равны `None`, тогда как у перечисления обязательно должно быть хотя бы одно из них",
  "Структура более синтаксически многословна для создания, чем перечисление"
]
context = """
Использование структур, содержащих типы `Option` в качестве полей, совершенно допустимо (в вопросе спрашивалось, какой аргумент **НЕ** является верным).
Но если ваша структура данных имеет инварианты, такие как "ровно одно из двух необязательных полей должно быть `Some`", то этот инвариант лучше обеспечивается с помощью перечисления.
"""