[[questions]]
id = "8ef2f170-71d9-4f17-a688-b99d8c8072a8"
type = "Tracing"
prompt.program = """
pub mod a {
  pub mod b {
    pub fn f() { println!(\"b1\"); }
    pub mod c {
      pub fn f() { println!(\"c1\"); }
    }
  }
  pub fn entry() { super::b::c::f(); }
}

pub mod b {
  pub fn f() { println!(\"b2\"); }
  pub mod c {
    pub fn f() { println!(\"c2\"); }
  }
}

fn main() {
  crate::a::entry();
}
"""
answer.doesCompile = true
answer.stdout = "c2"
context = """
`entry` использует путь `super::b::c::f`. `entry` находится внутри модуля `a`, поэтому `super` ссылается на родительский модуль `a`, которым является корневой крейт.
Затем дочерний `b` корня — это внешний модуль `b`, чей дочерний `c` содержит функцию `f`, которая выводит `\"c2\"`.
"""

[[questions]]
id = "153b12b3-4fbc-449c-99a6-7a2cd469df0f"
type = "Tracing"
prompt.program = """
pub mod point {
  #[derive(Debug)]
  pub struct Point(i32, i32);

  impl Point {
    pub fn origin() -> Self { Point(0, 0) }
  }
}

fn main() {
  let mut p = point::Point::origin();
  p.0 += 1;
  println!(\"{p:?}\");
}
"""
answer.doesCompile = false
answer.lineNumber = 12
context = """
Хотя структура `Point` и статический метод `origin` являются публичными, поле `i32` не помечено как `pub`. Поэтому прямой доступ к `p.0` за пределами модуля `point` запрещён.
Эта программа скомпилировалась бы, если бы строка 3 была изменена на `pub struct Point(pub i32, pub i32)`.
"""