[[questions]]
id = "904a0808-22d1-45e5-9611-cf143babbc41"
type = "MultipleChoice"
prompt.prompt = """
Каков правильный порядок, где "A > B" означает "A содержит B"?
"""
answer.answer = "пакет > крейт > модуль"
prompt.distractors = [ "модуль > крейт > пакет", "крейт > пакет > модуль" ]
context = """
Пакет — это верхнеуровневая организационная единица, содержащая крейты. Крейт содержит модули.
"""

[[questions]]
id = "d45c7cbe-6089-40b9-843c-fbb9ff48ca49"
type = "ShortAnswer"
prompt.prompt = """
Представьте, что вы видите пакет Rust `foobar` со следующими файлами:

```text
foobar
├── Cargo.toml
├── build.rs
└── src/
    ├── main.rs
    ├── util.rs
    ├── lib.rs
    └── bin/
        └── alt.rs
```

Сколько крейтов содержит этот пакет? Запишите ответ в виде цифры, например 0, 1 и так далее.
"""
answer.answer = "3"
context = """ 
`main.rs` создаёт бинарный крейт, `lib.rs` создаёт библиотечный крейт, а `bin/alt.rs` создаёт бинарный крейт. `util.rs` предположительно используется как модуль в одном из этих крейтов, но это не специальное имя файла, распознаваемое Rust, поэтому он не будет отдельным крейтом. `build.rs` — это скрипт сборки.
"""