[[questions]]
id = "6a94bc90-6cc5-4a47-838c-596d3747b7e4"
type = "ShortAnswer"
prompt.prompt = """
Представьте Rust-крейт со следующей структурой каталогов:

```text
foobar
├── Cargo.toml
└── src/
    ├── lib.rs
    ├── engine.rs
    └── engine/
        └── analysis.rs
```

Содержимое каждого файла:

```
// engine/analysis.rs
pub fn run() {}
```

```
// engine.rs
mod analysis;
pub use analysis::*;
```

```
// lib.rs
pub mod engine;
```

Допустим, другой разработчик на Rust использует библиотечный крейт `foobar` в отдельном пакете и хочет вызвать функцию `run`. 
Какой путь он должен написать?
"""
answer.answer = "foobar::engine::run"
answer.alternatives = ["foobar::engine::run()"]
context = """
Дерево модулей, сгенерированное этой структурой каталогов, выглядит так:

```text
foobar
└── engine
    └── run  
```

Следовательно, путь к `run` — это `foobar::engine::run`.
"""