[[questions]]
id = "23c95879-aae2-4121-bf89-21278f7b6ec6"
type = "MultipleChoice"
prompt.prompt = """
Какое из следующих утверждений НЕ является преимуществом использования модулей?
"""
answer.answer = "Модули повышают производительность во время выполнения взаимосвязанного кода в рамках одного модуля"
prompt.distractors = [
  "Модули группируют связанный код, что позволяет программистам легче работать над большим кодейсом",
  "Модули инкапсулируют детали реализации, которые не должны использоваться внешними клиентами",
  "Модули предоставляют область видимости для избежания конфликтов имен в разных частях кодейса"
]
context = """
Модули не влияют на время выполнения, они предназначены исключительно для организации на этапе компиляции.
"""