[[questions]]
id = "da6daf92-5b2c-4f8d-97de-6905dbc77936"
type = "MultipleChoice"
prompt.prompt = "Какое утверждение лучше всего объясняет, почему Rust не позволяет индексировать строки?"
answer.answer = "Индексация строк неоднозначна, потому что строки представляют несколько гранулярностей упорядоченных данных"
prompt.distractors = [
  "Индексация строк небезопасна, потому что может вызвать segmentation fault или переполнение буфера",
  "Индексация строк неэффективна, потому что строки заканчиваются нулём, поэтому их длину нельзя эффективно вычислить",
  "Индексация строк сделала бы Rust слишком простым в использовании, а разработчикам Rust нужна безопасность работы"
]
context = """
UTF-8 строку можно интерпретировать как последовательность байтов, символов или кластеров графем. Ни один из этих способов не является обязательно «основным» способом интерпретации строки, поэтому операция индексации по умолчанию не имеет смысла.
"""

[[questions]]
id = "9366278e-a3f5-4759-ac72-e3c7d248da44"
type = "MultipleChoice"
prompt.prompt = """
Какое утверждение лучше всего описывает разницу между типами среза строки `&str` и среза байтов `&[u8]`?
"""
answer.answer = "`&str` указывает на байты, которые всегда могут быть интерпретированы как UTF-8, тогда как `&[u8]` может быть любой последовательностью байтов"
prompt.distractors = [
  "`&str` всегда указывает на данные, хранящиеся в бинарном файле программы, тогда как `&[u8]` может храниться где угодно в памяти",
  "`&str` нельзя дальше нарезать, а `&[u8]` можно нарезать снова",
  "`&str` можно построить из `String`, тогда как `&[u8]` может происходить только из `Vec`"
]
context = """
`&str` — это обещание, что последовательность байтов, на которую он указывает, всегда будет валидным UTF-8. Поэтому программист, который хочет, например, вывести `&str`, никогда не должен проверять его валидность или беспокоиться о случайной интерпретации невалидной строки.
"""