[[questions]]
id = "1665d1ef-961f-4451-a988-ec46121531f9"
type = "MultipleChoice"
prompt.prompt = """
Какой вызов этой функции `find_until` вызовет панику во время выполнения?

```
fn find_until(v: &Vec<i32>, n: i32, til: usize) -> Option<usize> {
  for i in 0 .. til {
    if v[i] == n {
      return Some(i);
    }
  }
  return None;
}
```
"""
answer.answer = "`find_until(&vec![1, 2, 3], 4, 4)`"
prompt.distractors = [
  "`find_until(&vec![1, 2, 3], 0, 0)`",
  "`find_until(&vec![1, 2, 3], 3, 3)`",
  "`find_until(&vec![1, 2, 3], 1, 4)`"
]
context = """
Если `til = 4`, то для вектора длины 3 цикл `for` попытается получить доступ к элементу вектора по индексу `i = 3`, что выходит за границы.
Эта функция не паникует, если `n = 1`, потому что она возвращает значение, прежде чем достичь индекса вне границ.
"""

[[questions]]
id = "789dfffc-7556-443d-98ab-5d0a4db5c162"
type = "Tracing"
prompt.program = """
fn main() {
  let mut v = Vec::new();
  let s = String::from("Hello ");
  v.push(s);
  v[0].push_str("world");
  println!("original: {}", s);
  println!("new: {}", v[0]);
}
"""
answer.doesCompile = false
answer.lineNumber = 6
context = """
Метод `Vec::push` перемещает свой аргумент, поэтому `s` становится недоступным после вызова `v.push(s)`. Следовательно, вызов `println!("original: {}", s)` не является безопасным по владению.
"""

[[questions]]
id = "66270f68-3ad6-4e79-8c73-c04d2daf9792"
type = "Tracing"
prompt.program = """
fn main() {
  let v = vec![String::from("Hello ")];
  let mut s = v[0];
  s.push_str("world");
  println!("{s}");
}
"""
answer.doesCompile = false
answer.lineNumber = 3
context = """
Некопируемые типы нельзя переместить из вектора с помощью индексации. Только такие методы, как `Vec::remove`, позволяют переместить значение из вектора. В разделе 4.3 
["Копирование против перемещения из коллекции"](ch04-03-fixing-ownership-errors.html#fixing-an-unsafe-program-copying-vs-moving-out-of-a-collection)
приведено более глубокое объяснение, почему это так.
"""