[[questions]]
id = "79942534-f414-41e6-944f-96d57905632c"
type = "MultipleChoice"
prompt.prompt = "В чём разница между использованием `a + b` и `a.push_str(b)` для конкатенации двух строк?"
answer.answer = "`+` потребляет владение `a`, в то время как `push_str` — нет"
prompt.distractors = [
  "`push_str` более эффективна во время выполнения, чем `+`",
  "`push_str` потребляет владение `b`, в то время как `+` — нет",
  "Разницы нет, это псевдонимы одной и той же функции"
]
context = """
`push_str` принимает `&mut self`, в то время как `+` принимает `self`, поэтому `+` потребляет владение, а `push_str` — нет.
"""

[[questions]]
id = "f1ab2171-96f0-4380-b16d-9055a9a00415"
type = "ShortAnswer"
prompt.prompt = """
Каково максимальное количество раз выделение в куче может произойти в этой программе? Укажите ответ цифрами, например 0 или 1.

```
let s1 = String::from("tic");
let s2 = String::from("tac");
let s3 = String::from("toe");

let s = s1 + "-" + &s2 + "-" + &s3;
```
"""
answer.answer = "7"
context = """
Одно выделение для каждого вызова `String::from` и одно выделение каждый раз при вызове `+`.
"""