[[questions]]
id = "867e5d29-c1eb-44b3-99e3-bb2325b74e44"
type = "MultipleChoice"
prompt.prompt = """
**Программа 1:**

```ide
/// Удаляет все нули на месте из вектора целых чисел.
fn remove_zeros(v: &mut Vec<i32>) {
    for (i, t) in v.iter().enumerate().rev() {
        if *t == 0 {
            v.remove(i);
            v.shrink_to_fit();
        }
    }
}
```

Если вы попытаетесь скомпилировать эту функцию, какое из следующих описаний лучше всего соответствует ошибке компилятора, которую вы получите?
"""
answer.answer = "`v.remove(i)` не может заимствовать `v` как изменяемый"
prompt.distractors = [
  "`v` не живёт достаточно долго, чтобы вызвать `v.remove(i)`",
  "`t` не может быть разыменован, пока `i` жив",
  "`v.iter()` не может быть вызван для изменяемой ссылки"
]
context = """
Функция `v.iter()` не изменяемо заимствует вектор `v` на время цикла for. Однако `v.remove(i)` требует изменяемую ссылку на `v`. Поэтому `v.remove(i)` не может заимствовать `v` как изменяемый, так как это конфликтовало бы с итератором.
"""

[[questions]]
id = "dd1bd092-ef8d-4293-a4d6-6a59b5887e98"
type = "MultipleChoice"
prompt.prompt = """
**Программа 1:**

```ide
/// Удаляет все нули на месте из вектора целых чисел.
fn remove_zeros(v: &mut Vec<i32>) {
    for (i, t) in v.iter().enumerate().rev() {
        if *t == 0 {
            v.remove(i);
            v.shrink_to_fit();
        }
    }
}
```

Обычно, если вы пытаетесь скомпилировать эту функцию, компилятор возвращает следующую ошибку:

```text
error[E0502]: cannot borrow `*v` as mutable because it is also borrowed as immutable
 --> test.rs:5:13
  |
3 |     for (i, t) in v.iter().enumerate().rev() {
  |                   --------------------------
  |                   |
  |                   immutable borrow occurs here
  |                   immutable borrow later used here
4 |         if *t == 0 {
5 |             v.remove(i);
  |             ^^^^^^^^^^^ mutable borrow occurs here
```

Предположим, что компилятор НЕ отклонил эту функцию. Какая (если есть) из следующих программ
(1) пройдёт компилятор и (2) потенциально вызовет неопределённое поведение при выполнении?
Отметьте каждую программу, удовлетворяющую обоим критериям, ИЛИ отметьте "Ни одна из этих программ", если ни одна не удовлетворяет.
"""
answer.answer = [
"""
```
let mut v = vec![5, 5, 0];
remove_zeros(&mut v);
println!("{:?}", v);
```
""",
"""
```
let mut v = vec![1, 2, 0, 3];
remove_zeros(&mut v);
```
""", 
]
prompt.distractors = [
"""
```
let mut v = vec![1; 100];
remove_zeros(&mut v);
```
""",
"Ни одна из этих программ",
]
context = """
Чтобы нарушить безопасность памяти, `remove_zeros` должен быть вызван с вектором, содержащим ноль после первого элемента.
Вызов `v.shrink_to_fit()` освободит память, принадлежащую вектору (из-за изменения размера), что сделает недействительным
итератор `v.iter()`, содержащий указатель на старые данные. Обратите внимание, что чтение вектора `v` после вызова `remove_zeros`
не является существенным для нарушения безопасности, так как проблема внутренняя для `remove_zeros`.
"""

[[questions]]
id = "c7e7e1e1-2788-4dd9-9c18-436bc95b405f"
type = "MultipleChoice"
prompt.prompt = """
**Программа 1:**

```ide
/// Удаляет все нули на месте из вектора целых чисел.
fn remove_zeros(v: &mut Vec<i32>) {
    for (i, t) in v.iter().enumerate().rev() {
        if *t == 0 {
            v.remove(i);
            v.shrink_to_fit();
        }
    }
}
```

Какое из следующих исправлений (выделено жёлтым) лучше всего удовлетворяет трём критериям:
1. Исправленная функция проходит компилятор Rust,
2. Исправленная функция сохраняет намерение исходного кода и
3. Исправленная функция не вносит ненужную неэффективность
"""
answer.answer = """
```ide
fn remove_zeros(v: &mut Vec<i32>) {
    for `[i in (0 .. v.len()).rev()]` {
        if `[v[i]]` == 0 {
            v.remove(i);
            v.shrink_to_fit();
        }
    }
}
```
"""
prompt.distractors = [
"""
```ide
fn remove_zeros(v: &mut Vec<i32>) {
    for (i, t) in v`[.clone()]`.iter().enumerate().rev() {
        if *t == 0 {
            v.remove(i);
            v.shrink_to_fit();
        }
    }
}
```
""",
"""
```ide
fn remove_zeros(v: `[&]`Vec<i32>) `[-> Vec<i32>]` {
    `[let mut new_vec = Vec::new();]`
    for (i, t) in v.iter().enumerate().rev() {
        if *t `[!=]` 0 {
            `[new_vec.push(*t)]`
        }
    }
    `[new_vec]`
}
```
""",
"""
```ide
fn remove_zeros(v: `[Vec<i32>]`) {
    for (i, t) in v.iter().enumerate().rev() {
        if *t == 0 {
            v.remove(i);
            v.shrink_to_fit();
        }
    }
}
```
""",
]
context = """
Любая стратегия, требующая выделения нового вектора, либо через `Vec::clone`, либо через `Vec::new`, требует ненужного дополнительного выделения памяти.
Поэтому простейшая работающая стратегия — это только итерировать по индексам `0 .. v.len()`, что не заимствует `v`. Мы делаем это в обратном порядке, чтобы избежать удаления пропущенных индексов.

Как и в Проблеме 1, наиболее идиоматичная стратегия — это использовать встроенную функцию, которую мы не обсуждали,
[`Vec::retain`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.retain). Эта функция сохраняет только элементы вектора,
которые проходят проверку, но делает это с большей эффективностью использования памяти.
"""

[[questions]]
id = "fb0e3080-7cc8-4338-948e-fae693d137c8"
type = "MultipleChoice"
prompt.prompt = """
**Программа 2:**

```ide
/// Переворачивает элементы вектора на месте
fn reverse(v: &mut Vec<String>) {
    let n = v.len();
    for i in 0 .. n / 2 {
        std::mem::swap(&mut v[i], &mut v[n - i - 1]);
    }
}
```

Если вы попытаетесь скомпилировать эту программу, какое из следующих описаний лучше всего соответствует ошибке компилятора, которую вы получите?
"""
answer.answer = "не может заимствовать `v` как изменяемый дважды для `v[i]` и `v[n - i - 1]`"
prompt.distractors = [
  "не может заимствовать `v` как не изменяемый для `v.len()`, когда `v` является изменяемым заимствованием",
  "не может изменяемо заимствовать элемент `v[i]` изменяемого вектора"
]
context = """
Компилятор не учитывает конкретное значение индексов, используемых для доступа к массиву, поэтому `&mut v[i]`
и `&mut v[n - i - 1]` предполагаются как возможно ссылающиеся на один и тот же элемент. Поэтому мы получаем ошибку,
что `v` не может быть изменяемо заимствовано дважды.
"""

[[questions]]
id = "4c703871-3cc3-483f-beb5-876bdbcd223b"
type = "MultipleChoice"
prompt.prompt = """
**Программа 2:**

```ide
/// Переворачивает элементы вектора на месте
fn reverse(v: &mut Vec<String>) {
    let n = v.len();
    for i in 0 .. n / 2 {
        std::mem::swap(&mut v[i], &mut v[n - i - 1]);
    }
}
```

Обычно, если вы пытаетесь скомпилировать эту функцию, компилятор возвращает следующую ошибку:

```text
error[E0499]: cannot borrow `*v` as mutable more than once at a time
 --> test.rs:5:40
  |
5 |         std::mem::swap(&mut v[i], &mut v[n - i - 1]);
  |         --------------      -          ^ second mutable borrow occurs here
  |         |                   |
  |         |                   first mutable borrow occurs here
  |         first borrow later used by call
```

Предположим, что компилятор НЕ отклонил эту функцию. Какая (если есть) из следующих программ
(1) пройдёт компилятор и (2) потенциально вызовет неопределённое поведение при выполнении?
Отметьте каждую программу, удовлетворяющую обоим критериям, ИЛИ отметьте "Ни одна из этих программ", если ни одна не удовлетворяет.
"""
answer.answer = ["Ни одна из этих программ"]
prompt.distractors = [
"""
```
let mut v = vec![String::from("a"), String::from("b")];
let x = &v[0];
reverse(&mut v);
println!("{x}");
```
""",
"""
```
let mut v = vec![String::from("a"), String::from("b")];
reverse(&mut v);
```
""",
"""
```
let mut v = vec![String::from("a"), String::from("b")];
reverse(&mut v);
println!("{:?}", v);
```
""",
]
context = """
Эта функция не может вызвать нарушение безопасности памяти, потому что `i != n - i - 1` для всех `i`, поэтому две
изменяемые ссылки всегда ссылаются на разные элементы. Обратите внимание, что программа `let x = &v[0]` не скомпилируется,
так как проверка заимствований Rust не позволит вызвать `reverse`, пока `x` жив.
"""

[[questions]]
id = "380fc77f-190d-4386-9e0e-f9360bbbfd98"
type = "MultipleChoice"
prompt.prompt = """
**Программа 2:**

```ide
/// Переворачивает элементы вектора на месте
fn reverse(v: &mut Vec<String>) {
    let n = v.len();
    for i in 0 .. n / 2 {
        std::mem::swap(&mut v[i], &mut v[n - i - 1]);
    }
}
```

Какое из следующих исправлений (выделено жёлтым) лучше всего удовлетворяет трём критериям:
1. Исправленная функция проходит компилятор Rust,
2. Исправленная функция сохраняет намерение исходного кода и
3. Исправленная функция не вносит ненужную неэффективность
"""
answer.answer = """
```ide
fn reverse(v: &mut Vec<String>) {
    let n = v.len();
    for i in 0 .. n / 2 {
        `[let p1 = &mut v[i] as *mut String;]`
        `[let p2 = &mut v[n - i - 1] as *mut String;]`
        `[unsafe { std::ptr::swap_nonoverlapping(p1, p2, 1); }]`
    }
}
```
"""
prompt.distractors = [
"""
```ide
fn reverse(v: &mut Vec<String>) {
    let n = v.len();
    `[let mut v2 = v.clone();]`
    for i in 0 .. n / 2 {
        std::mem::swap(&mut v[i], &mut `[v2]`[n - i - 1]);
    }
}
```
""",
"""
```ide
fn reverse(v: `[&Vec<String>]`) -> `[Vec<String>]` {
    let n = v.len();
    `[let mut v2 = Vec::new();]`    
    for _ in 0 .. `[n]` {
        `[v2.push(v.pop().unwrap());]`
    }
    `[v2]`
}
```
""",
"""
```ide
fn reverse(v: &mut Vec<String>) {
    let n = v.len();    
    for i in 0 .. n / 2 {
        `[let s1 = v[i].clone();]`
        `[let s2 = v[n - i - 1].clone();]`
        `[v[i] = s2;]`
        `[v[n - i - 1] = s1;]`
    }
}
```
""",
]
context = """
В ситуации, когда проверка заимствований отклоняет операцию, которая на самом деле безопасна и не имеет обходного пути, тогда
небезопасный код иногда приемлем, если критически важно избежать выделений памяти. 
В этом конкретном случае вы должны на самом деле использовать [`Vec::swap`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.swap), который внутренне реализован
с тщательно протестированным `unsafe` кодом, подобным коду выше. 
Но вообще, если стандартная библиотека не поддерживает ваш случай использования, то `unsafe` может быть приемлем, если используется правильно.
"""