[[questions]]
id = "18bf21e1-4e1a-4e98-861d-c7032710a8ad"
type = "ShortAnswer"
prompt.prompt = "Как называется переменная окружения, которую нужно установить в `1`, чтобы увидеть трассировку стека при панике?"
answer.answer = "RUST_BACKTRACE"
context = """
Например, вы можете запустить из командной строки: `RUST_BACKTRACE=1 cargo run`
"""

[[questions]]
id = "23cabd75-88f5-4ff8-8bf5-4bd4d1a9e64a"
type = "MultipleChoice"
prompt.prompt = "Что из перечисленного НЕ является хорошей причиной для использования паники?"
answer.answer = "Программа достигла состояния ошибки, которое должно быть передано функции-вызывающей"
prompt.distractors = [
  "Программа собирается выполнить опасную операцию",
  "Программа должна прекратить выполнение как можно скорее",
  "Программа достигла невосстановимого состояния ошибки"
]
context = """
Паника не должна использоваться для передачи сбоя *внутри* программы. По умолчанию предполагается, что функции-вызывающие не будут пытаться перехватывать паники.
"""