[[questions]]
id = "31c55174-3fdf-4a21-959c-bb4056def264"
type = "MultipleChoice"
prompt.prompt = """
Программист на Rust разрабатывает библиотеку для создания интерфейсов командной строки. 
В рамках этой библиотеки он реализует функцию для разбора флагов командной строки, предоставленных пользователем. 
Какая реализация будет наиболее подходящей для этой предметной области?

```
fn parse_flag_v1(flag: &str) -> Result<String, String> {
  match flag.strip_prefix("--") {
    Some(no_dash) => Ok(no_dash.to_string()),
    None => Err(format!("Invalid flag {flag}"))
  }
}

fn parse_flag_v2(flag: &str) -> String {
  match flag.strip_prefix("--") {
    Some(no_dash) => no_dash.to_string(),
    None => panic!("Invalid flag {flag}")
  }
}
```
"""
answer.answer = "`parse_flag_v1`"
prompt.distractors = [ "`parse_flag_v2`" ]
prompt.answerIndex = 0
context = """
Здесь программист, скорее всего, захочет использовать *восстанавливаемую* ошибку (`Result`). Если пользователь CLI передаёт некорректно отформатированный флаг,
то библиотека CLI, возможно, захочет предоставить дополнительную справку, например, отобразить возможный набор флагов. Паника заставит приложение
показать только сообщение о панике и, вероятно, обеспечит худший пользовательский опыт.
"""