[[questions]]
id = "91fb1ec6-fb11-4b6f-88df-dbc921a4108f"
type = "MultipleChoice"
prompt.prompt = "Для произвольного выражения `e` типа `Result<T, E>`, какой фрагмент кода лучше всего представляет, как транслируется `e?`?"
answer.answer = """
```
match e {
  Ok(x) => x,
  Err(err) => { return Err(err); }
}
```
  """
prompt.distractors = [
  """
```
if let Err(err) = e {
  return Err(err);
}
```
  """,
  """
```
e.unwrap()
```
  """,
  """
```
match e {
  Ok(x) => x,
  Err(err) => panic!("{err}")
}
```
  """,
]
context = """
Если `e` имеет тип `Result`, то `e?` извлекает значение внутри `Ok`, если это возможно, иначе возвращает `Err` из текущей функции.
"""

[[questions]]
id = "0ea46358-f560-4d3e-85d2-a1806eb7c797"
type = "Tracing"
prompt.program = """
// предположим, что hello.txt содержит "will"

fn read_username_from_file() -> Option<String> {
  let mut username_file = File::open("hello.txt")?;
  let mut username = String::new();
  username_file.read_to_string(&mut username)?;
  Some(username)
}

fn main() {
  println!("{}", read_username_from_file().unwrap()); 
}
"""
answer.doesCompile = false
answer.lineNumber = 4
context = """
`File::open` возвращает `Result`, но тип возвращаемого значения `read_username_from_file` ожидает `Option`. Поэтому недопустимо использовать оператор `?`, пока `Result` не будет преобразован в `Option` (например, с помощью метода `Result::ok`).
"""