[[questions]]
id = "8f9e0e79-f4a7-4056-b35e-f7ae65b78888"
type = "MultipleChoice"
prompt.prompt = "Какое из этих утверждений лучше всего описывает, почему `File::open` возвращает `Result`, а не `Option`?"
answer.answer = "Потому что `Result` может представлять, почему операция завершилась неудачей, а открытие файла может завершиться неудачей по многим причинам"
prompt.distractors = [
  "Потому что `Result` представляет возможность неудачи, в то время как `Option` не может представлять неудачи",
  "Потому что `Result` использует меньше байтов во время выполнения, чем `Option`, для представления неудач",
  "Потому что `Result` представляет ошибки так же, как системные вызовы"
]
context = """
`Option` может только показать, что операция завершилась неудачей, но `Result` может объяснить, почему операция завершилась неудачей.
"""