[[questions]]
id = "c4adb1a8-ca6a-43c1-ae34-54302f674ece"
type = "Tracing"
prompt.program = """
trait MakeNoise {
  fn make_noise(&self) {
    println!("(silence)");
  }
}

struct Dog {}
struct Cat {}

impl MakeNoise for Dog {
  fn make_noise(&self) {
    println!("bark");
  }
}

impl MakeNoise for Cat {}

fn main() {
  let dog = Dog {};
  let cat = Cat {};
  dog.make_noise();
  cat.make_noise();
}
"""
answer.doesCompile = true
answer.stdout = "bark\n(silence)"
context = """
Реализация `MakeNoise` предоставляет конкретную реализацию для `Dog` и использует реализацию по умолчанию для `Cat`.
Поэтому вызов `make_noise` для каждого выводит `bark` и `(silence)` соответственно. 
"""

[[questions]]
id = "783f2485-e5b9-483b-8368-064366c77285"
type = "MultipleChoice"
prompt.prompt = "Ниже приведены утверждения о том, какие реализации типажей разрешены в Rust. Выберите каждое верное утверждение."
prompt.distractors = [
  "Вы можете реализовать внешний типаж для внешнего типа",
  "Вы можете реализовать локальный типаж для внешнего типа",
  "Вы можете реализовать локальный типаж для локального типа"
]
answer.answer = [
  "Вы можете реализовать локальный типаж для внешнего типа",
  "Вы можете реализовать локальный типаж для локального типа"
]
context = """
«Правило сироты» требует, чтобы вы не могли реализовать внешний типаж для внешнего типа, 
чтобы обеспечить отсутствие конфликтов реализаций, если два крейта предоставляют конфликтующие реализации.
"""