[[questions]]
id = "8b7f93c3-efb0-44e2-a0ca-b45e35620b30"
type = "MultipleChoice"
prompt.prompt = "Какой вид ошибки программирования время жизни предназначено для предотвращения?"
answer.answer = "Использование ссылки на объект после освобождения его памяти"
prompt.distractors = [
  "Использование результата вычисления, которое может завершиться ошибкой, до проверки возможности ошибки",
  "Выход за границы массива при индексации (переполнение буфера)",
  "Выделение недостаточного объема памяти для объекта"
]
context = "Время жизни помогает определить, как долго объект \"жив\", и переживают ли ссылки на этот объект сам объект."

[[questions]]
id = "77cf924a-ece1-4119-a762-f5f03536b4e1"
type = "Tracing"
prompt.program = """
fn shortest<'a, 'b>(x: &'a str, y: &'b str) -> &'a str {
  if x.len() < y.len() {
    x
  } else {
    y
  }
}

fn main() {
  println!("{}", shortest("hello", "rust"));
}
"""
answer.doesCompile = false
answer.lineNumber = 5
context = "Если сигнатура типа говорит, что функция должна возвращать ссылку с временем жизни `'a`, то возвращать ссылку с другим временем жизни `'b` недопустимо, т.е. `y` здесь."