[[questions]]
id = "9ff33b87-38e2-471b-8ca4-9c31a6431376"
type = "MultipleChoice"
prompt.prompt = """
**Программа 1:**

```ide
/// Возвращает n-й по величине элемент в срезе
fn find_nth<T: Ord + Clone>(elems: &[T], n: usize) -> T {
    elems.sort();
    let t = &elems[n];
    return t.clone();
}
```

Если бы вы попытались скомпилировать эту программу, какое из следующих описаний лучше всего соответствует ошибке компилятора, которую вы получили?
"""
answer.answer = "не может заимствовать `elems` как изменяемый для `sort`"
prompt.distractors = [
  "не может переместить из разделяемой ссылки для `clone`",
  "не может переместить из разделяемой ссылки в выражении `&elems[n]`",
  "время жизни `T` должно переживать `&[T]`",
]
context = """
Метод `slice::sort` ожидает изменяемую ссылку на срез, но вместо этого получает неизменяемую ссылку.
"""

[[questions]]
id = "3ee8d846-d282-4de1-8e83-5ca0bc44fc13"
type = "MultipleChoice"
prompt.prompt = """
**Программа 1:**

```ide
/// Возвращает n-й по величине элемент в срезе
fn find_nth<T: Ord + Clone>(elems: &[T], n: usize) -> T {
    elems.sort();
    let t = &elems[n];
    return t.clone();
}
```

Обычно, если вы попытаетесь скомпилировать эту функцию, компилятор вернёт следующую ошибку:

```text
error[E0596]: cannot borrow `*elems` as mutable, as it is behind a `&` reference
 --> test.rs:3:5
  |
3 |     elems.sort();
  |     ^^^^^^^^^^^^ `elems` is a `&` reference, so the data it refers to cannot be borrowed as mutable
```

Предположим, что компилятор НЕ отклонил эту функцию. Какая (если есть) из следующих программ
(1) пройдёт компиляцию и (2) возможно вызовет неопределённое поведение при выполнении?
Отметьте каждую программу, удовлетворяющую обоим критериям, ИЛИ отметьте "Ни одна из этих программ", если ни одна не удовлетворяет.
"""
answer.answer = ["Ни одна из этих программ"]
prompt.distractors = [
"""
```
let v = vec![5, 4, 3, 2, 1];
find_nth(&v, 10);
```
""",
"""
```
let v = vec![5, 4, 3, 2, 1];
find_nth(&v, 0);
println!("{}", v[0]);
```
""",
"""
```
let v = vec![5, 4, 3, 2, 1];
let n = &v[0];
find_nth(&v, 0);
println!("{}", n);
```
""",
]
context = """
Эта программа технически безопасна в отношении памяти, потому что `slice::sort` способен только перемещать
элементы, не освобождая их. Например, `&v[0]` гарантированно указывает на 
*какое-то* число после вызова `find_nth`, даже если это не *исходное* число.

Обратите внимание, что `find_nth(&v, 10)` не вызывает неопределённого поведения, потому что Rust выполняет проверки
при доступе к массиву, поэтому вычисление `&v[10]` приведёт к панике.
"""

[[questions]]
id = "d070eb9e-4527-453a-8c9b-698739a3dd6a"
type = "MultipleChoice"
prompt.prompt = """
**Программа 1:**

```ide
/// Возвращает n-й по величине элемент в срезе
fn find_nth<T: Ord + Clone>(elems: &[T], n: usize) -> T {
    elems.sort();
    let t = &elems[n];
    return t.clone();
}
```

Какое из следующих исправлений (выделенных жёлтым) лучше всего удовлетворяет этим трём критериям:
1. Исправленная функция проходит компиляцию Rust,
2. Исправленная функция сохраняет намерение исходного кода, и
3. Исправленная функция не вносит ненужных неэффективностей
"""
answer.answer = """
```ide
fn find_nth<T: Ord + Clone>(elems: &[T], n: usize) -> T {
    `[let mut elem_refs: Vec<&T> = elems.iter().collect();]`
    `[elem_refs.sort();]`
    let t = `[elem_refs[n]]`;
    return t.clone();
}
```
"""
prompt.distractors = [
"""
```ide
fn find_nth<T: Ord + Clone>(`[elems: &mut [T]]`, n: usize) -> T {
    elems.sort();
    let t = &elems[n];
    return t.clone();
}
```
""",
"""
```ide
fn find_nth<T: Ord + Clone>(elems: &[T], n: usize) -> T {
    `[let mut elems = elems.to_vec();]`
    elems.sort();
    let t = &elems[n];
    return t.clone();
}
```
""",
"""
```ide
fn find_nth<`[T: Ord]`>(`[mut elems: Vec<T>]`, n: usize) -> T {
    elems.sort();
    let t = `[elems.remove(n)]`;
    return `[t]`;
}
```
""",
]
context = """
Функция вроде `find_nth` явно предназначена быть функцией только для чтения, т.е. для
извлечения некоторого свойства входной последовательности. Любое решение, которое изменяет или отбрасывает входные данные, поэтому не сохраняет намерение исходной функции, даже если
оно более эффективно, чем создание вспомогательного вектора.

Создание `Vec<&T>` предпочтительнее создания `Vec<T>`, поскольку если `T` большой, то
`elems.to_vec()` может быть дорогим. Однако, если бы мы знали, что `T: Copy`, то `to_vec`
было бы предпочтительнее для уменьшения количества разыменований указателей внутри `elems.sort()`.
"""

[[questions]]
id = "95979d75-5823-4059-a1cf-7e0eba69b41a"
type = "MultipleChoice"
prompt.prompt = """
**Программа 2:**

```ide
struct TestResult {
    /// Оценки студента на тесте
    scores: Vec<usize>,

    /// Возможное значение для подгонки всех оценок
    curve: Option<usize>
}
impl TestResult {  
    pub fn get_curve(&self) -> &Option<usize> { 
        &self.curve 
    }

    /// Если есть подгонка, то увеличивает все 
    /// оценки на значение подгонки
    pub fn apply_curve(&mut self) {
        if let Some(curve) = self.get_curve() {
            for score in self.scores.iter_mut() {
                *score += *curve;
            }
        }
    }
}
```

Если бы вы попытались скомпилировать эту программу, какое из следующих описаний лучше всего соответствует ошибке компилятора, которую вы получили?
"""
answer.answer = "в `apply_curve`, не может заимствовать `self.scores` как изменяемый для `iter_mut`"
prompt.distractors = [
  "в `get_curve`, не может вернуть ссылку на локальную переменную `self.curve`",
  "в `apply_curve`, не может заимствовать `self` как неизменяемый для `get_curve`",
  "в `apply_curve`, `*score` не может быть изменён"
]
context = """
Из-за упрощения времени жизни, функция `get_curve` имеет сигнатуру типа `get_curve<'a>(&'a self) -> &'a Option<usize>`.
Это означает, что вызов `self.get_curve()` расширяет всё заимствование `self`, а не только `self.curve`.
Поэтому `self` неизменно заимствован внутри области видимости `let Some(curve) = ...`, и `self.scores.iter_mut()`
не может быть вызван.
"""

[[questions]]
id = "dcb42a15-d9b7-437d-95ec-f000b64ce277"
type = "MultipleChoice"
prompt.prompt = """
**Программа 2:**

```ide
struct TestResult {
    /// Оценки студента на тесте
    scores: Vec<usize>,

    /// Возможное значение для подгонки всех оценок
    curve: Option<usize>
}
impl TestResult {  
    pub fn get_curve(&self) -> &Option<usize> { 
        &self.curve 
    }

    /// Если есть подгонка, то увеличивает все 
    /// оценки на значение подгонки
    pub fn apply_curve(&mut self) {
        if let Some(curve) = self.get_curve() {
            for score in self.scores.iter_mut() {
                *score += *curve;
            }
        }
    }
}
```

Обычно, если вы попытаетесь скомпилировать эту функцию, компилятор вернёт следующую ошибку:

```text
error[E0502]: cannot borrow `self.scores` as mutable because it is also borrowed as immutable
  --> test.rs:17:26
   |
16 |         if let Some(curve) = self.get_curve() {
   |                              ---------------- immutable borrow occurs here
17 |             for score in self.scores.iter_mut() {
   |                          ^^^^^^^^^^^^^^^^^^^^^^ mutable borrow occurs here
18 |                 *score += *curve;
   |                           ------ immutable borrow later used here
```

Предположим, что компилятор НЕ отклонил эту функцию. Какая (если есть) из следующих программ
(1) пройдёт компиляцию и (2) возможно вызовет неопределённое поведение при выполнении?
Отметьте каждую программу, удовлетворяющую обоим критериям, ИЛИ отметьте "Ни одна из этих программ", если ни одна не удовлетворяет.
"""
answer.answer = ["Ни одна из этих программ"]
prompt.distractors = [
"""
```
let mut result = TestResult { 
    scores: vec![20, 50, 30], 
    curve: Some(10) 
};
result.apply_curve();
```
""",
"""
```
let mut result = TestResult { 
    scores: vec![20, 50, 30], 
    curve: Some(10) 
};
let x = &result.scores[0];
result.apply_curve();
println!("{}", x);
```
""",
"""
```
let mut result = TestResult { 
    scores: vec![20, 50, 30], 
    curve: Some(10) 
};
result.apply_curve();
println!("{:?}", result.scores);
```
""",
]
context = """
Эта программа на самом деле безопасна в том виде, в котором написана. Это ограничение проверки заимствований, не понимающей, что `get_curve`
заимствует только `curve` и не затрагивает `scores`. Однако, в теории, если `get_curve` изменить так, чтобы возвращала ссылку
на что-то с `self.scores`, то безопасность памяти потенциально может быть нарушена.
"""

[[questions]]
id = "aa93c497-9864-4799-b69b-7de42c158f2a"
type = "MultipleChoice"
prompt.prompt = """
**Программа 2:**

```ide
struct TestResult {
    /// Оценки студента на тесте
    scores: Vec<usize>,

    /// Возможное значение для подгонки всех оценок
    curve: Option<usize>
}
impl TestResult {  
    pub fn get_curve(&self) -> &Option<usize> { 
        &self.curve 
    }

    /// Если есть подгонка, то увеличивает все 
    /// оценки на значение подгонки
    pub fn apply_curve(&mut self) {
        if let Some(curve) = self.get_curve() {
            for score in self.scores.iter_mut() {
                *score += *curve;
            }
        }
    }
}
```

Какое из следующих исправлений (выделенных жёлтым) лучше всего удовлетворяет этим трём критериям:
1. Исправленная функция проходит компиляцию Rust,
2. Исправленная функция сохраняет намерение исходного кода, и
3. Исправленная функция не вносит ненужных неэффективностей
"""
answer.answer = """
```ide
pub fn apply_curve(&mut self) {
    if let Some(curve) = `[self.curve]` {
        for score in self.scores.iter_mut() {
            *score += curve;
        }
    }
}
```
"""
prompt.distractors = [
"""
```ide
pub fn apply_curve(&mut self) {
    if let Some(curve) = self.get_curve()`[.as_ref()]` {
        for score in self.scores.iter_mut() {
            *score += *curve;
        }
    }
}
```
""",
"""
```ide
pub fn apply_curve(&mut self) {
    if let Some(curve) = self.get_curve() {
        for score in self.scores`[.clone()]`.iter_mut() {
            *score += *curve;
        }
    }
}
```
""",
"""
```ide
pub fn apply_curve(&mut self) {
    if let Some(curve) = self.get_curve() {
        for score in self.scores`[.iter()]` {
            *score += *curve;
        }
    }
}
```
""",
]
context = """
Встраивая определение `get_curve` в `apply_curve`, проверка заимствований понимает, что `self.curve` не является `self.scores`,
поэтому позволяет функции скомпилироваться. Это распространённый обходной путь для такого типа ограничения проверки заимствований.

Другой вариант — использовать тот факт, что `self.curve` дёшево копируется, и применить [`Option::copied`](https://doc.rust-lang.org/std/option/enum.Option.html#method.copied),
что освободит заимствование `self` сразу после вызова `.copied()`.
"""