[[questions]]
id = "0aad53ff-89d7-4d14-8e3d-c17809220252"
type = "ShortAnswer"
prompt.prompt = """
Представьте, что вы используете стороннюю функцию, чью реализацию вы не знаете, но чья сигнатура типов такая:

```
fn mystery<T>(x: T) -> T {
  // ????
}
```

Затем вы вызываете `mystery` так:

```
let y = mystery(3);
```

Если `mystery` не использует небезопасный код, то значение `y` должно быть :
"""
answer.answer = "3"
context = """
Единственно возможная функция (без небезопасного кода), имеющая сигнатуру `T -> T`, — это функция тождественного отображения:

```
fn mystery<T>(x: T) -> T {
  x
}
```

Функция, конечно, может паниковать или печатать, но возвращаемое значение может быть только входным. `mystery` не знает, что такое `T`, поэтому у `mystery` нет способа создать или изменить значение `T`.
См. [Теоремы бесплатно!](https://dl.acm.org/doi/pdf/10.1145/99370.99404) для большего количества примеров этой идеи.

**3 действительно правильный ответ! Если вы не согласны с ответом, пожалуйста, не отправляйте отчет об ошибке!**
"""

[[questions]]
id = "40ae0cfe-3567-4d05-b0d9-54d612a2d654"
type = "Tracing"
prompt.program = """
fn print_slice<T>(v: &[T]) {
  for x in v {
    println!("{x}");
  }
}

fn main() {
  print_slice(&[1, 2, 3]);
}
"""
answer.doesCompile = false
answer.lineNumber = 3
context = """
Если тип является обобщённым (как `T`), мы не можем предполагать ничего о нём, включая возможность преобразовать его в строку. Поэтому `println!("{x}")` неверно, так как `x: &T`.
"""

[[questions]]
id = "694bb2d0-f2e6-4b0b-a3e7-2d9f9e8b3d09"
type = "Tracing"
prompt.program = """
struct Point<T> { x: T, y: T }

impl Point<i32> {
  fn f(&self) -> &i32 { &self.y }
}

impl<T> Point<T> {
  fn f(&self) -> &T { &self.x }
}

fn main() {
  let p: Point<i32> = Point { x: 1, y: 2 };
  println!("{}", p.f());
}
"""
answer.doesCompile = false
answer.lineNumber = 8
context = """
Эти определения `f` конфликтуют, и у Rust нет способа определить, какой `f` следует использовать при вызове `p.f()`. Поэтому это ошибка компиляции.
"""