[[questions]]
id = "a2a1546b-27bf-47d2-a1bc-86d777573f40"
type = "Tracing"
prompt.program = """
use std::fmt::Display;
fn displayable<T: Display>(t: T) -> impl Display { t }

fn main() {
  let s = String::from("hello");
  let mut s2 = displayable(s);
  s2.push_str(" world");
  println!("{s2}");
}
"""
answer.doesCompile = false
answer.lineNumber = 7
context = """
Поскольку `displayable` возвращает `impl Display`, мы знаем лишь, что `s2` — *некоторый* тип, реализующий типаж `Display`,
а не что это `String`, у которого есть метод `push_str`. Поэтому мы не можем вызвать `s2.push_str(..)`. Если бы возвращаемый
тип `displayable` был `-> T`, то эта программа скомпилировалась бы.
"""

[[questions]]
id = "8b35f91c-ced2-4b8f-bf1c-90550f2b744b"
type = "MultipleChoice"
prompt.prompt = """
Каков наименьший набор ограничений типажа на `T`, необходимый для того, чтобы эта функция прошла проверку типов?
```
fn f<T: /* ??? */>(t: &T) {
  let t2 = t.clone();
  println!("{t2}");
}
```
"""
answer.answer = "`Clone + Display`"
prompt.distractors = [ "(без ограничений)", "`Clone`", "`Clone + Display + Debug`" ]
context = """
Поскольку вызывается `clone` и в форматтере используются фигурные скобки `{}`, то `T` должен быть `Clone` и `Display`.
"""