[[questions]]
id = "3da96b29-d975-4cd8-a8eb-b1a6bd9b5c0a"
type = "MultipleChoice"
prompt.prompt = """
Какое из перечисленных НЕ является веской причиной для размещения модульных тестов в `#[cfg(test)] mod tests { ... }`?
"""
answer.answer = "Это даёт тестам доступ к приватным функциям"
prompt.distractors = [
  "Это может уменьшить размер сгенерированных артефактов компилятора",
  "Это может ускорить компиляцию",
  "Это отделяет вспомогательные функции для тестов от кода библиотеки"
]
context = """
Все модульные тесты в данном файле имеют доступ к приватным функциям этого файла, независимо от того, находятся они в `mod tests` или нет.
"""