[[questions]]
id = "7a7bb518-b06e-4756-9510-6a8d0d1c84fa"
type = "ShortAnswer"
prompt.prompt = "Какая аннотация добавляется к функции, чтобы указать, что это модульный тест?"
answer.answer = "#[test]"
context = "Это сообщает тестовому механизму cargo рассматривать функцию как тест, а не как код библиотеки."

[[questions]]
id = "cd77485f-723a-4978-8da6-c4ca3df44c44"
type = "MultipleChoice"
prompt.prompt = """
Предположим, у вас есть функция с сигнатурой типа:

```
fn f(x: usize) -> Result<usize, String>;
```

И вы хотите проверить, что `f(0)` возвращает `Err(_)`. 
Какой из следующих способов НЕ является допустимым для такой проверки?
"""
answer.answer = """
```
#[test]
#[should_err]
fn test() -> Result<usize, String> {
  f(0)
}
```
  """
prompt.distractors = [
  """
```
#[test]
fn test() {
  assert!(f(0).is_err());
}
```
  """,
  """
```
#[test]
#[should_panic]
fn test() { 
  f(0).unwrap();
}
```
  """,
  """
```
#[test]
fn test() {
  assert!(match f(0) {
    Ok(_) => false,
    Err(_) => true
  });  
}
```
  """
]
context = "`should_err` не существует в Rust — любой тест, возвращающий `Result`, должен возвращать `Ok`, чтобы пройти."