[[questions]]
id = "affe428d-0a8e-430b-9567-99e6b7563c0f"
type = "MultipleChoice"
prompt.prompt = """
При запуске `cargo test` без дополнительной конфигурации, какие из следующих действий могут работать некорректно, если их выполняют несколько тестов одновременно?
"""
answer.answer = "Запись текста в один файл"
prompt.distractors = [
  "Вывод строк в stdout",
  "Паника через panic",
  "Чтение данных из одной базы данных"
]
context = """
Тесты выполняются параллельно по умолчанию, поэтому действия, которые не являются потокобезопасными (такие как запись в один файл), могут вызвать состояние гонки.
"""

[[questions]]
id = "19e292f4-4bc4-4868-a58a-edf62c3e3b2a"
type = "ShortAnswer"
prompt.prompt = """
Рассмотрим программу со следующими модульными тестами:

```
#[test]
fn test_the_logger() { /* ... */ }

#[test]
fn test_the_database() { /* ... */ }

#[test]
fn test_logger_and_database() { /* ... */ }
```

Какую *самую короткую* строку вы можете передать в `cargo test <строка>`, чтобы *только* `test_the_logger` и `test_the_database` были выполнены?
"""
answer.answer = "h"
context = """
Самая короткая подстрока, которая не содержится в `test_logger_and_database`, но содержится в `test_the_logger` и `test_the_database` — это "h" (средний символ в "the").
"""