[[questions]]
id = "e6cbd582-9692-4045-a984-8770a12e1b95"
type = "MultipleChoice"
prompt.prompt = """
Что из перечисленного наилучшим образом описывает причину, по которой Rust выводит типы аргументов/возвращаемых значений для замыканий, но не для функций верхнего уровня?
"""
answer.answer = "Функции верхнего уровня могут быть частью внешнего интерфейса библиотеки, в то время как замыкания не могут быть напрямую экспонированы"
prompt.distractors = [
  "Из-за проблемы остановки Rust математически не может выводить типы функций верхнего уровня",
  "Для обратной совместимости с более старыми версиями Rust",
  "Всё, что можно присвоить переменной, может иметь вывод типов, а функции верхнего уровня нельзя присвоить переменной"
]
context = """
Rust теоретически мог бы предоставлять вывод типов для функций верхнего уровня. Функциональные языки, такие как Haskell и OCaml, имеют такую возможность.
Однако разработчики Rust сознательно приняли решение требовать аннотации типов для функций верхнего уровня, чтобы способствовать ясности на уровне интерфейса: у функции всегда будет ровно тот тип, который указан в её объявлении.
"""

[[questions]]
id = "f844d1c2-3f63-4cdb-b16e-6e818e996e0d"
type = "MultipleChoice"
prompt.prompt = """
Rust позволяет сопоставление с образцом в аргументах замыканий, включая использование нижнего подчеркивания. Например, вы можете написать следующее:

```rust
let f = |_| (); // иногда называется "туалетным замыканием"
let s = String::from("Hello");
f(s);
```

Что из перечисленного наилучшим образом описывает связь между `f` и `s` в этой программе?
"""
answer.answer = "`f` приводит к немедленному уничтожению `s`"
prompt.distractors = [
  "`f` не оказывает никакого влияния на `s`",
  "`f` читает `s`, а затем отбрасывает результат",
  "`f` захватывает `s` в своём окружении"
]
context = """
Туалетное замыкание аналогично [`std::mem::drop`](https://doc.rust-lang.org/std/mem/fn.drop.html), то есть функции, которая перемещает аргумент и приводит к его уничтожению.
"""