[[questions]]
id = "a055fa7c-89e2-467e-8458-62cbf3ffb8bf"
type = "Tracing"
prompt.program = """
fn main() {
    let mut s = String::from("Hello");
    let mut add_suffix = || s.push_str(" world");
    println!("{s}");
    add_suffix();
}
"""
answer.doesCompile = false
answer.lineNumber = 5
context = """
`add_suffix` изменяемо заимствует `s` между своим определением и использованием, поэтому `println` (чтение `s`) недопустимо.
"""

[[questions]]
id = "266d3cb3-de76-4b91-bd13-c3d6cb9e7fd7"
type = "Tracing"
prompt.program = """
fn main() {
    let mut s = String::from("Hello");
    let add_suffix = |s: &mut String| s.push_str(" world");
    println!("{s}");
    add_suffix(&mut s);
}
"""
answer.doesCompile = true
answer.stdout = "Hello"
context = """
Поскольку `add_suffix` не захватывает `s`, можно читать `s` перед изменением с помощью `add_suffix`.
"""

[[questions]]
id = "0f298680-d870-47a1-962c-1c668f75cb68"
type = "MultipleChoice"
prompt.prompt = """
Рассмотрим следующий API:

```rust
/// Executes a function with a mutable reference to each element of a vector
fn for_each_mut<T, F: ___(&mut T)>(v: &mut Vec<T>, mut f: F) {
    for x in v.iter_mut() {
        f(x);
    }
}
```

Какой из следующих функциональных типажей наиболее подходит для заполнения пропуска?
"""
answer.answer = "`FnMut`"
prompt.distractors = ["`Fn`", "`FnOnce`"]
context = """
`f` вызывается несколько раз, поэтому `FnOnce` не подходит. И `Fn`, и `FnMut` могут работать, а `FnMut` менее ограничивающий, поэтому `FnMut` наиболее подходит.
"""

[[questions]]
id = "65f574b1-b418-4abe-852e-8b14d88368a7"
type = "MultipleChoice"
prompt.prompt = """
Рассмотрим следующую структуру:

```rust
pub struct Analyzer<F> {
    postprocess: F
}

impl<F: ___(i32) -> i32> Analyzer<F> {
    fn process(&self, n: i32) -> i32 { /* .. */ }
    pub fn pipeline(&self, n: i32) -> i32 {
        let n = self.process(n);
        (self.postprocess)(n)
    }
}
```

Какой из следующих функциональных типажей наиболее подходит для заполнения пропуска?
"""
answer.answer = "`Fn`"
prompt.distractors = ["`FnMut`", "`FnOnce`"]
context = """
`pipeline` может вызываться несколько раз, поэтому `FnOnce` не подходит.
`pipeline` принимает неизменяемую ссылку на `self`. Если бы `postprocess` был `FnMut`, его нельзя было бы вызвать внутри `pipeline`.
Следовательно, здесь наиболее подходит `Fn`.
"""