[[questions]]
id = "d50dd9fb-f84c-4748-9e45-cd3dc8d5fb47"
type = "MultipleChoice"
prompt.prompt = """
Что из перечисленного лучше всего описывает, почему итераторы называют «ленивыми»?
"""
answer.answer = "Итератор не производит эффектов, пока вы не вызовете методы, извлекающие элементы из итератора"
prompt.distractors = [
    "Итератор создаёт копию каждого элемента, по которому проходит", 
    "Итератор принимает владение последовательностью элементов, по которым проходит", 
    "Итератор будет проходить только по заданному количеству элементов"
]
context = """
«Ленивый» обычно означает «не выполняет работу, пока его об этом не попросят», и итераторы не выполняют никаких вычислений, пока не будет вызван `Iterator::next`.
"""

[[questions]]
id = "19eac65e-44ad-4349-9632-47bdbb519d46"
type = "MultipleChoice"
prompt.prompt = """
Истина/ложь: эти два фрагмента кода семантически эквивалентны, где `iter` — это итератор.

Фрагмент 1:
```
while let Some(x) = iter.next() {
    f(x);
}
```

Фрагмент 2:
```
for x in iter {
    f(x);
}
```
"""
answer.answer = "Истина"
prompt.distractors = ["Ложь"]
context = """
Цикл `for` — это синтаксический сахар для `while let`, который сам является сахаром для `loop` и `break`.
"""

[[questions]]
id = "ff652580-b487-4379-bd70-652f5803321d"
type = "Tracing"
prompt.program = """
fn main() {
    let v = vec![1, 2, 3, 4];
    let a: Vec<_> = v.iter().filter(|x: &&i32| *x % 2 == 0).map(|x: &i32| x * 2).collect();
    let b: Vec<_> = v.iter().map(|x: &i32| x * 2).filter(|x: &i32| x % 2 == 0).collect();
    println!("{} {}", a[0], b[0]);
}
"""
answer.doesCompile = true
answer.stdout = "4 2"
context = """
Порядок итераторов имеет значение — filter и map не то же самое, что map и filter!

Возможно, вы wondered, почему в первом filter используется `*x`, а во втором — нет. 
`v.iter()` создаёт `Iterator<Item = &i32>`. Вызов `.filter()` принимает `Iterator<Item = T>` на вход
и передаёт `&T` в свою предикат-функцию. Поэтому `x: &&i32` в строке 3. Стандартная библиотека Rust реализует
оператор остатка `%` для `&i32` слева ([см. документацию](https://doc.rust-lang.org/std/ops/trait.Rem.html#impl-Rem%3Ci32%3E-for-%26'a+i32)),
но не для `&&i32`. Поэтому нам нужно один раз разыменовать `x`, чтобы использовать его в выражении `*x % 2`.

Напротив, в строке 4, когда `.map()` принимает `Iterator<Item = T>` на вход, он передаёт `T` в своё замыкание.
Поэтому замыкание в `map` принимает `&i32` на вход. Оператор умножения `*` реализован для `&i32`,
поэтому `x` не нужно разыменовывать в `x * 2`. Операция `x * 2` производит значение типа `i32`, поэтому
результат map — это `Iterator<Item = i32>`. Затем `filter` принимает `x : &i32`, который также не требует
разыменования для `x % 2`. Теперь вы знаете!
"""