[[questions]]
id = "20846719-fe7b-48b8-abfd-9c5f1174472f"
type = "MultipleChoice"
prompt.prompt = """
Рассмотрим рабочее пространство со следующей структурой:

```
├── Cargo.lock
├── Cargo.toml
└── crates
    ├── a
    |   ├── lib.rs
    |   └── Cargo.toml
    └── b
        ├── lib.rs
        └── Cargo.toml
```

С следующим содержимым в каждом файле:

```
// crates/b/lib.rs
pub fn f() {}
```

```toml
# crates/a/Cargo.toml
[dependencies]
b = {path = "../b"}
```

Какой из следующих путей является правильным для обращения к `f` внутри `a/lib.rs`?
"""
answer.answer = "`b::f`"
prompt.distractors = [
    "`crates::b::f`",
    "`workspace::b::f`",
    "`super::b::f`",
]
context = """
С точки зрения `a`, `b` является внешним крейтом, как и любой другой, поэтому вы не используете префикс для доступа к его элементам.
"""

[[questions]]
id = "bc8a69b2-d9a8-4438-8657-391c3fda5ed9"
type = "ShortAnswer"
prompt.prompt = """
Рассмотрим рабочее пространство с тремя пакетами `a`, `b` и `c`. Их соответствующие манифесты:

```toml
# a/Cargo.toml
[dependencies]
rand = "0.8.4"

# b/Cargo.toml
[dependencies]
rand = "0.7.3"

# c/Cargo.toml
[dependencies]
rand = "0.8.5"
```

Сколько различных версий `rand` будет использоваться при компиляции всех пакетов в рабочем пространстве? 
Укажите ответ цифрой, например, 0, 1 и т.д.
"""
answer.answer = "2"
context = """
Согласно правилам семантического версионирования, `a` и `c` будут использовать последний патч минор-версии `0.8`.
`b` будет использовать последний патч минор-версии `0.7`. Таким образом, всего будет использоваться две версии.
"""