[[questions]]
id = "7e4eeb62-55c2-443b-a8cc-fba060501245"
type = "MultipleChoice"
prompt.prompt = """
Предположим, вы публикуете библиотеку `foobar v0.1.0`. После запуска `cargo publish` вы обнаруживаете ошибку в одной
из ваших функций. Что из перечисленного наилучшим образом описывает, как перезаписать опубликованный крейт на той же версии `v0.1.0`?
"""
answer.answer = "Невозможно перезаписать опубликованный крейт на заданную версию"
prompt.distractors = [
    "Добавить флаг `--overwrite-published` к команде `cargo publish`",
    "Войти на Crates.io и удалить `v0.1.0` опубликованного крейта",   
    "Запустить `cargo yank`, а затем запустить `cargo publish`"
]
context = """
Crates.io не позволяет перезаписывать опубликованные версии. Лучшим вариантом в такой ситуации является замена (yank) ошибочной версии
и последующая публикация новой версии, например `v0.1.1`.
"""

[[questions]]
id = "84ac16a8-2460-4baf-8913-06da6e3603e6"
type = "MultipleChoice"
prompt.prompt = """
Какой из перечисленных шагов НЕ требуется для публикации крейта на Crates.io?
"""
answer.answer = "Добавление документации к каждой публичной функции в крейте"
prompt.distractors = [
    "Добавление лицензии в раздел `[package]` файла `Cargo.toml`",    
    "Регистрация и вход в систему на Crates.io",
    "Выбор имени крейта, которое не зарегистрировано на Crates.io"
]
context = """
Добавление документации к публичным функциям, безусловно, рекомендуется, но по умолчанию не требуется. Обратите внимание, что если
вы хотите, чтобы Rust считал недокументированный код ошибкой, вы можете добавить следующее объявление в корень вашей библиотеки:

```
#![deny(missing_docs)]
```
"""