[[questions]]
id = "e2df0a8a-7bdd-40a3-9918-e4a856978cbb"
type = "MultipleChoice"
prompt.prompt = """
Предположим, вы публикуете библиотеку и хотите написать документацию о всей библиотеке вверху файла `lib.rs`.
Документация должна иметь префикс в виде следующего синтаксиса комментария:
"""
answer.answer = "`//!`"
prompt.distractors = [
    "`///`",
    "`//`",    
]
context = """
`//!` подходит для документации на уровне модуля, в то время как `///` предназначен для документирования отдельных элементов, таких как функции.
"""

[[questions]]
id = "cfb65011-0578-4032-8aaa-b346b091602b"
type = "MultipleChoice"
prompt.prompt = """
Предположим, вы создаете библиотеку `worldly` и в файле `lib.rs` содержится следующий код:

    /// Adds the string "world" to `s`.
    ///
    /// # Example
    /// ```
    /// let mut s = String::new();
    /// worldly::add_world(&mut s);
    /// assert_eq!(s, "Hello world");
    /// ```
    pub fn add_world(s: &mut String) {
        s.push_str("world");
    }

    #[test]
    fn test_add_world() {
        let mut s = String::new();
        add_world(&mut s);
        assert_eq!(s, "world");
    }

Если вы запустите `cargo test`, провалится ли какой-нибудь тест?
"""
answer.answer = "Да"
prompt.distractors = [
    "Нет",    
]
context = """
Некорректный пример будет запущен как doc-test и приведет к падению `cargo test`.
"""