[[questions]]
id = "8282968d-b1d3-42b4-b128-f97b951db4c6"
type = "Tracing"
prompt.program = """
struct Example(i32);
impl Drop for Example {
    fn drop(&mut self) {
        self.0 += 1;
        println!("drop {}", self.0);
    }
}
fn main() {
    let e = Example(0);
    drop(e);
    drop(e);
}
"""
answer.doesCompile = false
answer.lineNumber = 11
context = """
Владеемое значение не может быть уничтожено дважды, поэтому вызов drop второй раз является ошибкой компиляции.
"""

[[questions]]
id = "b9121273-1c1e-4e99-9cff-a23f845aaeeb"
type = "MultipleChoice"
prompt.prompt = """
Рассмотрим этот фрагмент кода, который выделяет строку:

```rust
fn main() {
    let mut s = String::new();
    ____
}
```

Какие из следующих операций являются допустимыми для заполнения пропуска, которые приведут к уничтожению `s`?
"""
answer.answer = ["`drop(s);`", "`(|_| ())(s);`", "`{ s };`"]
prompt.distractors = [
    "`s.drop();`",    
]
context = """
Любое использование `s`, которое перемещает его и отбрасывает результат, приведет к уничтожению `s`. Однако `s.drop()` нельзя вызвать напрямую.
"""