[[questions]]
id = "01904807-74c7-41ad-8d8b-cfb30e5ce10c"
type = "MultipleChoice"
prompt.prompt = """
Какое из следующих утверждений наилучшим образом описывает концепцию *внутренней изменяемости* (interior mutability) в Rust?
"""
answer.answer = "Разрешение изменения данных через неизменяемую ссылку"
prompt.distractors = [
    "Оборачивание `небезопасного` (unsafe) кода в безопасный API",
    "Разрешение изменения данных внутри структуры данных",
    "Использование проверки заимствований (borrow checker) для обеспечения безопасности памяти во время выполнения"
]
context = """
Основная идея внутренней изменяемости — это получение значения типа `&T` и возможность 
безопасно изменять данные внутри `T`.
"""

[[questions]]
id = "380cd865-76c5-419c-8961-af4c59d2ab71"
type = "MultipleChoice"
prompt.prompt = """
Рассмотрим API, который отслеживает количество вызовов определённого метода:

```
struct Api {
    count: ???
}

impl Api {
    fn some_method(&self) {
        // увеличить count
        // остальная часть метода...
    }    
}
```

Предположим, что count представлен как `usize`. Какой из следующих вариантов будет наиболее подходящим типом-обёрткой для использования в этой ситуации?
"""
answer.answer = "`RefCell<usize>`"
prompt.distractors = [
    "`Rc<usize>`",
    "`Box<usize>`",
    "Никакой, `usize` подходит"
]
context = """
Здесь `RefCell` полезен для изменения внутреннего поля, даже если `some_method` принимает 
неизменяемую ссылку в качестве входного параметра. Если внутреннее поле — просто целое число, 
ещё лучшим выбором типа был бы `Cell<usize>` или `AtomicUsize`.
"""

[[questions]]
id = "d4ae1b8e-79a7-4485-828f-fb30cdeb29d5"
type = "MultipleChoice"
prompt.prompt = """
Рассмотрим следующую некорректную реализацию `RefCell`, которая не проверяет, 
заимствовано ли внутреннее значение:

```
use std::cell::UnsafeCell;
struct BadRefCell<T>(UnsafeCell<T>);
impl<T> BadRefCell<T> {
    pub fn borrow_mut(&self) -> &mut T {
        unsafe { &mut *self.0.get() }
    }
}
```

Теперь предположим, у нас есть `BadRefCell` следующим образом:

```
let v = BadRefCell(UnsafeCell::new(vec![1, 2, 3]));
```

Какой из следующих фрагментов кода нарушит безопасность памяти при использовании этого API?
"""
answer.answer = """
```
let v1 = v.borrow_mut();
let n = &v1[0];
v.borrow_mut().push(0);
println!("{n}");
```
"""
prompt.distractors = [
"""
```
drop(v.borrow_mut());
drop(v.borrow_mut());
```
""",
"""
```
let v1 = v.borrow_mut();
let v2 = v.borrow_mut();
v1.push(0);
v2.push(0);
```
""",
"""
```
v.borrow_mut().push(0);
let n = v.borrow_mut()[0];
println!("{n}");
```
"""
]
context = """
`BadRefCell` позволяет нам иметь две изменяемые ссылки на базовые данные одновременно,
что допускает нарушение безопасности памяти, например, перераспределение вектора (reallocation) 
при удержании ссылки на его содержимое.
"""