[[questions]]
id = "6f3c2a68-24f7-439b-9fe0-426abd27e487"
type = "Tracing"
prompt.program = """
fn main() {
    let mut n = 1;
    let b = Box::new(&mut n);
    **b += 1;
    println!("{}", n);
}
"""
answer.doesCompile = true
answer.stdout = "2"
context = """
Коробка может хранить изменяемую ссылку, поэтому двойное разыменование `b` возвращает `n`.
"""

[[questions]]
id = "57595a80-c79f-4aae-a1d4-cdaf212d7c21"
type = "ShortAnswer"
prompt.prompt = """
Предположим, у вас есть программа с переменной:

```
let x: [Box<(usize, usize)>; 4] = /* ... */
```

Для целевой архитектуры 64 бита, каков минимально возможный размер в памяти (в байтах) `x` в стеке?
Укажите ответ цифрами, например 0, 1 и т.д.
"""
answer.answer = "32"
context = """
Коробка содержит указатель, который занимает 8 байт на 64-битной архитектуре. Массив из 4 указателей, следовательно, имеет как минимум 4 * 8 = 32 байта.
"""