[[questions]]
id = "53cb3740-2962-4379-a25f-a65e72812a95"
type = "Tracing"
prompt.program = """
use std::thread;
fn main() {
    let mut n = 1;
    let t = thread::spawn(move || {
        n = n + 1;
        thread::spawn(move || {
            n = n + 1;
        })
    });
    n = n + 1;
    t.join().unwrap().join().unwrap();
    println!("{n}");
}
"""
answer.doesCompile = true
answer.stdout = "2"
context = """
Ключевое слово `move` приводит к копированию `n` в замыкание, поэтому присваивания
`n = n + 1` внутри `thread::spawn` не влияют на внешний `n`.
"""

[[questions]]
id = "c2a84e6d-8143-4944-bf20-b00e49144ac9"
type = "MultipleChoice"
prompt.prompt = """
Рассмотрим этот пример из текста, где вектор неправильно захватывается потоком:

```
use std::thread;

fn main() {
    let v = vec![1, 2, 3];

    let handle = thread::spawn(|| {
        println!("Here's a vector: {:?}", v);
    });

    handle.join().unwrap();
}
```

Компилятор Rust выводит эту диагностику:

```text
note: function requires argument type to outlive `'static`
 --> src/main.rs:6:18
  |
6 |       let handle = thread::spawn(|| {
  |  __________________^
7 | |         println!("Here's a vector: {:?}", v);
8 | |     });
  | |______^
```

Напомним, что `'static` — это время жизни ссылок, которые действительны на протяжении всей программы.

Что лучше всего описывает примечание "function requires argument type to outlive `'static`"?
"""
answer.answer = "Rust не знает, как долго будет работать поток, поэтому захваты потока должны жить вечно"
prompt.distractors = [
    "Замыкание, переданное в `thread::spawn`, не может принимать аргументы",
    "Вектор `v` содержит значения, время жизни которых не превышает `'static`",
    "Замыкание может захватывать только строковые константы типа `&'static str`"
]
context = """
Если замыкание захватывает ссылку на значение, время жизни которого меньше `'static`, возможно, что поток будет существовать дольше значения и нарушит безопасность памяти. Обратите внимание, что [`thread::scope`](https://doc.rust-lang.org/std/thread/fn.scope.html) можно использовать, чтобы разрешить потокам захватывать нестатические ссылки, статически ограничивая время жизни потока.
"""