[[questions]]
id = "43081862-aac8-4e18-9c55-1107ea4c7cc1"
type = "MultipleChoice"
prompt.prompt = """
Представьте, что вы проектируете API для подключения к базе данных следующим образом:

```
struct DbConnection { /* ... */ }
impl DbConnection {
    fn query(&self) -> DbResult {
        /* ... */
    }
}
```

Ваша база данных не поддерживает конкурентные запросы из одного подключения. 
Какой из перечисленных маркерных типажей должен реализовать `DbConnection`?
"""
answer.answer = "`Send`"
prompt.distractors = [
    "`Send` и `Sync`",
    "`Sync`",
    "Ни `Send`, ни `Sync`"
]
context = """
Отправка `DbConnection` между потоками допустима, поэтому `DbConnection` должен реализовывать `Send`.
Но было бы неверно, например, разделять `Arc<Database>` так, чтобы несколько потоков конкурентно
вызывали `db.query()`, поэтому `DbConnection` не должен реализовывать `Sync`.
"""