[[questions]]
id = "ceb96826-6c98-40e1-bff4-0bb61f35679d"
type = "MultipleChoice"
prompt.prompt = """
В некоторых API для конкурентности мьютекс отделён от данных, которые он защищает. Например, представьте гипотетический API Mutex:

```
let mut data = Vec::new();
let mx: Mutex = Mutex::new();
{
    let _guard = mx.lock();
    data.push(0);
}
```

Что из перечисленного лучше всего описывает, почему Rust использует `Mutex<T>` вместо просто `Mutex`?
"""
answer.answer = "Чтобы предотвратить доступ к данным мьютекса без его блокировки"
prompt.distractors = [
    "Чтобы требовать меньше вызовов методов мьютекса",
    "Чтобы повысить эффективность конкурентных программ с мьютексами",
    "Чтобы предотвратить перемещение данных мьютекса между потоками"
]
context = """
Дизайн `Mutex<T>` гарантирует, что к данным мьютекса можно получить доступ только тогда, когда мьютекс заблокирован, и, наоборот, что мьютекс разблокируется, как только данные становятся недоступными.
"""

[[questions]]
id = "e5ac0c92-4694-4647-bd20-67825fe038b7"
type = "Tracing"
prompt.program = """
use std::{sync::Arc, thread};

fn main() {
    let s = String::from("Hello world");
    let a = Arc::new(&s);
    let a2 = Arc::clone(&a);
    let t = thread::spawn(move || a2.len());
    let len = t.join().unwrap();
    println!("{} {}", a, len);
}
"""
answer.doesCompile = false
answer.lineNumber = 7
context = """
`Arc` всё ещё небезопасен для использования, если его данные содержат ссылку, поскольку ссылка может (теоретически) стать недействительной до того, как все потоки, содержащие `Arc`, завершат выполнение.
"""