[multipart]
q = """
**Контекст:** Вы проектируете библиотеку сериализации, которая преобразует типы данных Rust в форматы, такие как JSON.

**Функциональность:** Типаж `Serialize`, который могут реализовывать сериализуемые типы, и функция `to_json`, которая преобразует сериализуемые типы в JSON.

**Дизайны:** Ниже представлены несколько предложенных дизайнов для реализации функциональности.

```
// Option 1: types serialize to a `Value` enum
pub enum Value {
	String(String),
	Number(isize)
}

pub trait Serialize {
	fn serialize(&self) -> Value;
}

fn value_to_json(value: Value) -> String {
	/* .. */
}

pub fn to_json(data: impl Serialize) -> String {
    let value = data.serialize();
    value_to_json(value)
}


// Option 2: types serialize via calls to a `Serializer` interface
pub trait Serialize {
	fn serialize<S: Serializer>(&self, serializer: &mut S);
}

pub trait Serializer {
	fn serialize_string(&mut self, s: &str);
	fn serialize_number(&mut self, n: isize);
}

struct JsonSerializer { buffer: String };
impl Serializer for JsonSerializer {
	/* .. */
}

pub fn to_json(data: impl Serialize) -> String {
	let mut serializer = JsonSerializer { buffer: String::new() };
	data.serialize(&mut serializer);
	serializer.buffer
}
```
"""

[[questions]]
type = "MultipleChoice"
multipart = "q"
prompt.prompt = """
Выберите каждый вариант дизайна, который удовлетворяет следующему требованию:

**Требование:** Должно быть возможно добавить новый формат данных без необходимости изменять код в существующих реализациях типажа `Serialize`.
"""
prompt.distractors = []
prompt.sortAnswers = true
answer.answer = ["1", "2"]
context = """
Оба дизайна достаточно слабо связаны, так что каждый новый формат данных независим от любых реализаций `Serialize`. Для Варианта 1,
каждый формат данных преобразует `Value` в представление формата. `Value` выступает в качестве границы модуля.

Для Варианта 2, нет явного промежуточного представления сериализованного значения, а скорее каждая реализация `Serialize` явно обобщена
по любому выбору `S`, который реализует `Serializer`.
"""
id = "66e036c9-91a0-4611-8110-967b5ed1a514"

[[questions]]
type = "MultipleChoice"
multipart = "q"
prompt.prompt = """
Выберите каждый вариант дизайна, который удовлетворяет следующему требованию:

**Требование:** Процесс сериализации должен потреблять как можно меньше памяти.
"""
prompt.distractors = ["1"]
prompt.sortAnswers = true
answer.answer = ["2"]
context = """
Вариант 1 сериализует данные, сначала преобразуя структуру данных в промежуточное представление, `Value`, а затем преобразуя `Value` в конечный формат.
Эта промежуточная структура данных потребляет память, которая не нужна Варианту 2, где данные преобразуются напрямую в конечный формат.
"""
id = "eaa95520-1b72-4f7d-a600-5444b6368785"


[[questions]]
multipart = "q"
type = "MultipleChoice"
prompt.prompt = """
Выберите каждый вариант дизайна, который удовлетворяет следующему требованию:

**Требование:** Когда один и тот же тип данных сериализуется в несколько форматов, это должно увеличивать размер скомпилированного бинарного файла как можно меньше.
"""
prompt.distractors = ["2"]
prompt.sortAnswers = true
answer.answer = ["1"]
context = """
С Вариантом 1 существует только одна инстанциация `Serialize`, которая преобразует тип `T` в `Value`. Поскольку Вариант 2 обобщен по сериализаторам `S`,
то каждый раз, когда `T::serialize` вызывается с новым `S`, компилятор Rust выполнит мономорфизацию нового экземпляра `T::serialize`, что увеличит размер
бинарного файла по сравнению с Вариантом 1.
"""
id = "2751731e-7d18-46a1-aaea-b5734bf51c80"