[multipart]
q = """
**Контекст:** Вы проектируете простую систему событий, которая вызывает функции обратного вызова в ответ на события.

**Функциональность:** Структура `Events` предоставляет функции для регистрации обратных вызовов.
Обратный вызов либо параллелизуемый (может выполняться в нескольких потоках), либо последовательный (должен выполняться только в главном потоке).

**Варианты проектирования:** Ниже представлены несколько предложенных вариантов реализации функциональности.

```
pub struct Events {
	// ...
}

// Вариант 1: параллельный и последовательный — это два отдельных метода
impl Events {
	pub fn register<E, F: Fn(E)>(&mut self, f: F) { /* .. */ }
	pub fn register_sequential<E, F: Fn(E)>(&mut self, f: F) { /* .. */ }
}

// Вариант 2: параллельный и последовательный — это два элемента перечисления
pub enum Callback<F> {
	Parallel(F),
	Sequential(F)
}
impl Events {
	pub fn register<E, F: Fn(E)>(&mut self, f: Callback<F>) { /* .. */ }
}

// Вариант 3: параллельный и последовательный — это маркеры в методе трейта
pub trait Register<Marker, F, E> {
	fn register(&mut self, f: F);
}
pub struct Parallel;
pub struct Sequential;
impl<F, E> Register<Parallel, F, E> for Events 
where F: Fn(E) {
	fn register(&mut self, f: F) { /* .. */ }
}
impl<F, E> Register<Sequential, F, E> for Events 
where F: Fn(Sequential, E) {
	fn register(&mut self, f: F) { /* .. */ }
}
```
"""

[[questions]]
type = "MultipleChoice"
multipart = "q"
prompt.prompt = """
Выберите каждый вариант проектирования, который удовлетворяет следующему требованию:

**Требование:** Обратный вызов по умолчанию должен считаться параллелизуемым, и API должно отражать это поведение по умолчанию.
"""
prompt.distractors = ["2"]
prompt.sortAnswers = true
answer.answer = ["1", "3"]
context = """
Сначала представьте, как бы выглядела регистрация обратного вызова в каждом варианте.

```rust
// Вариант 1
events.register(|e: OnClick| { /* .. */ });
events.register_sequential(|e: OnClick| { /* .. */ })

// Вариант 2
events.register(Callback::Parallel(|e: OnClick| { /* .. */ }));
events.register(Callback::Sequential(|e: OnClick| { /* .. */ }));

// Вариант 3
events.register(|e: OnClick| { /* .. */ });
events.register(|_: Sequential, e: OnClick| { /* .. */ });
```

Из этих вариантов Варианты 1 и 3 показывают, что параллельный режим является режимом по умолчанию, поскольку он соответствует самому простому варианту.
Для последовательного требуется либо использовать более длинное имя метода (`_sequential`), либо тип-маркер (`_: Sequential)`.

Вариант 2 не явно указывает, что параллельный должен быть по умолчанию, потому что в `register` необходимо передавать и `Parallel`, и `Sequential`.
"""
id = "4a32bad8-fee7-45b5-80ef-775d059aab48"

[[questions]]
type = "MultipleChoice"
multipart = "q"
prompt.prompt = """
Выберите каждый вариант проектирования, который удовлетворяет следующему требованию:

**Требование:** API должно экспортировать как можно меньше методов.
"""
prompt.distractors = ["1"]
prompt.sortAnswers = true
answer.answer = ["2", "3"]
context = """
Варианты 2 и 3 экспортируют только один метод `register`. Вариант 1 требует экспорта двух методов с разными именами.
"""
id = "eaeafdad-ac3a-4d92-85eb-995991a81c2d"


[[questions]]
multipart = "q"
type = "MultipleChoice"
prompt.prompt = """
Выберите каждый вариант проектирования, который удовлетворяет следующему требованию:

**Требование:** API должно как можно меньше полагаться на систему вывода типов компилятора.
"""
prompt.distractors = ["3"]
prompt.sortAnswers = true
answer.answer = ["1", "2"]
context = """
Варианты 1 и 2 не требуют значительного вывода типов, кроме определения типа функции `F`.

Вариант 3 использует трюк с перегрузкой, создавая трейт `Register`, параметризованный по "типу-маркеру".
Вспомните два его вызова register:
```
events.register(|e: OnClick| { /* .. */ })
events.register(|_: Sequential, e: OnClick| { /* .. */ })
```

Они выглядят так, как будто используют одну и ту же реализацию, но на самом деле относятся к разным реализациям одного и того же метода.
Эта реализация полагается на то, что компилятор выведет тип `Marker` при разрешении, какая реализация `Register` соответствует каждому вызову `.register(..)`. Поэтому, если наша цель — *не* полагаться на вывод типов, то Вариант 3 неподходящ.
"""
id = "e0c4f766-b82a-496a-b669-ea9e0a367af7"