[[questions]]
id = "2c6d6e2e-ad6e-4e98-bf88-8cada144ebee"
type = "MultipleChoice"
prompt.prompt = """
**Программа 1:**

```ide
/// Добавляет объект, реализующий Display, в вектор 
/// объектов типажа Display
use std::fmt::Display;
fn add_displayable<T: Display>(
    v: &mut Vec<Box<dyn Display>>, 
    t: T
) {
    v.push(Box::new(t));
}
```

Если попытаться скомпилировать эту программу, какое из следующих описаний лучше всего соответствует ошибке компилятора?
"""
answer.answer = "тип `T` не живёт достаточно долго при приведении к объекту типажа"
prompt.distractors = [
  "тип `T` может быть динамически размещён и не может быть приведён к объекту типажа",
  "тип `T` не может быть помещён в Box, если содержит ссылку",
  "тип `T` не переживает время жизни ссылки `&mut Vec<..>`"
]
context = """
При приведении `Box<T>` к `Box<dyn Display>` (неявно в `v.push(..)`) Rust требует, чтобы объект типажа `dyn Display`
переживал вектор. Однако время жизни `T` не указано, поэтому `T` может не проживать достаточно долго.
"""


[[questions]]
id = "36da4652-baeb-47a6-9ee1-1448b02cbe8e"
type = "MultipleChoice"
prompt.prompt = """
**Программа 1:**

```ide
/// Добавляет объект, реализующий Display, в вектор 
/// объектов типажа Display
use std::fmt::Display;
fn add_displayable<T: Display>(
    v: &mut Vec<Box<dyn Display>>, 
    t: T
) {
    v.push(Box::new(t));
}
```

Обычно при попытке скомпилировать эту функцию компилятор возвращает следующую ошибку:

```text
error[E0310]: параметр типа `T` может не проживать достаточно долго
 --> test.rs:6:12
  |
6 |     v.push(Box::new(t));
  |            ^^^^^^^^^^^
```

Предположим, что компилятор НЕ отклонил эту функцию. Какая (если есть) из следующих программ
(1) пройдёт компиляцию и (2) возможно вызовет неопределённое поведение при выполнении?
Отметьте каждую программу, удовлетворяющую обоим критериям, ИЛИ отметьте "Ни одна из этих программ", если ни одна не удовлетворяет.
"""
answer.answer = [
"""
```
let mut v: Vec<Box<dyn Display>> = Vec::new();
{
    let n = 0;
    add_displayable(&mut v, &n);
}
println!("{}", v[0]);
```
"""
]
prompt.distractors = [
  "Ни одна из этих программ",
"""
```
let mut v: Vec<Box<dyn Display>> = Vec::new();
{
    let s = String::from("Hello world");
    add_displayable(&mut v, s);
}
println!("{}", v[0]);
```
""",
"""
```
let mut v: Vec<Box<dyn Display>> = Vec::new();
add_displayable(&mut v, 5);
```
"""
]
context = """
Эта программа небезопасна для памяти. Чтобы создать нарушение безопасности памяти, программа должна создать тип `T`, который содержит
ссылки, не переживающие вектор. Например, добавление `&n`, где `n` выходит из области видимости до `v`, означает, что
последующее использование `v[0]` является чтением освобождённой памяти.
"""


[[questions]]
id = "2da21d0e-5722-4908-b528-dc87bbce1faf"
type = "MultipleChoice"
prompt.prompt = """
**Программа 1:**

```ide
/// Добавляет объект, реализующий Display, в вектор 
/// объектов типажа Display
use std::fmt::Display;
fn add_displayable<T: Display>(
    v: &mut Vec<Box<dyn Display>>, 
    t: T
) {
    v.push(Box::new(t));
}
```

Какое из следующих исправлений (подсвечено жёлтым) лучше всего удовлетворяет трём критериям:
1. Исправленная функция проходит компиляцию Rust,
2. Исправленная функция сохраняет замысел исходного кода и
3. Исправленная функция не вносит ненужных неэффективностей
"""
answer.answer = """
```ide
fn add_displayable<`['a]`, T: Display `[+ 'a]`>(
    v: &mut Vec<Box<dyn Display `[+ 'a]`>>, 
    t: T
) {
    v.push(Box::new(t));
}
```
"""
prompt.distractors = [
"""
```ide
fn add_displayable<T: Display `[+ 'static]`>(
    v: &mut Vec<Box<dyn Display>>, 
    t: T
) {
    v.push(Box::new(t));
}
```
""",
"""
```ide
fn add_displayable<T: Display `[+ Clone]`>(
    v: &mut Vec<Box<dyn Display>>, 
    t: T
) {
    v.push(Box::new(`[t.clone()]`));
}
```
""",
"""
```ide
fn add_displayable<`['a]`, T: Display `[+ 'a]`>(
    v: &`['a]` mut Vec<Box<dyn Display>>, 
    t: T
) {
    v.push(Box::new(t));
}
```
""",
]
context = """
Наиболее идиоматичное исправление — указать, как время жизни `T` должно соотноситься со временем жизни объекта типажа `dyn Display`.
Здесь это означает добавление параметра времени жизни `'a`, указание, что `T` переживает `'a`, и что объекты типажа также живут как минимум
`'a`. 

Использование ограничения `'static` — то же самое, но хуже: это просто менее выразительно, запрещая объектам типажа в векторе
когда-либо содержать ссылки. Помещение времени жизни `'a` на ссылку `&'a mut Vec<..>` неверно и не исправляет ошибку компиляции.
"""