[[questions]]
id = "d19f9e83-d4c2-41d5-9fc7-81db5135eb1e"
type = "MultipleChoice"
prompt.prompt = """
В примере из этого раздела у записи в блоге могло быть одно из трёх состояний: `Draft`, `PendingReview` и `Published`. В примере каждое состояние было представлено как структура, а переходы между состояниями — как методы типажа, возвращающие объекты типажа.

Альтернативная реализация могла бы представить состояния как перечисление, например:

```
enum BlogState {
    Draft,
    PendingReview,
    Published
}

impl Post {
    fn request_review(&mut self) {
        use BlogState::*;
        self.state = match self.state {
            Draft => PendingReview,
            PendingReview => PendingReview,
            Published => Published
        }
    }
}
```

Какие из перечисленных причин являются вескими для предпочтения представления на основе структур/типажей перед представлением на основе перечисления?
"""
answer.answer = [
    "Клиент API может добавить новое состояние в систему",
    "Добавление нового состояния не требует изменения методов для каждого другого состояния"
]
prompt.distractors = [
    "Использование `match` работает медленнее, чем динамическая диспетчеризация",
    "Клиент API может добавить новый метод для всех состояний в системе"
]
context = """
Подход на основе структур/типажей является расширяемым в том смысле, что клиент API потенциально может создать новое состояние (например, `Retracted`), не изменяя базовую функциональность API. При добавлении этого состояния методы для других состояний менять не нужно. В то время как с перечислениями клиент не может добавить новую ветвь в перечисление. Более того, все выражения `match` должны быть обновлены при добавлении состояния.

`match` вряд ли будет работать медленнее, чем динамическая диспетчеризация. `match` — это простая ветвление на основе тега перечисления, в то время как динамическая диспетчеризация требует слоя косвенности через виртуальную таблицу объекта типажа с неинлайнированными вызовами функций.

Клиент API не может добавить новый *метод* для существующих состояний в подходе на основе структур/типажей, он может только добавлять новые состояния. Методы фиксированы определением типажа автора API. Обратите внимание, что вы могли бы добавить новый метод, который строится только на существующих методах, через расширяющие типажи, например:

```
trait StateExt {
    fn request_review_twice(self: Box<Self>) -> Box<dyn State>;
}

impl<S: State> StateExt for S {
    fn request_review_twice(self: Box<Self>) -> Box<dyn State> {
        self.request_review().request_review()
    }
}
```

Но такие расширения не могут читать приватные данные состояний.
"""