[[questions]]
id = "a4680619-9533-4cbb-a785-7b73570168af"
type = "MultipleChoice"
prompt.prompt = """
Какие из перечисленных аспектов объектно-ориентированного программирования реализует Rust?
"""
answer.answer = [
    "Объекты (структуры) с методами",
    "Инкапсуляция приватных данных",
]
prompt.distractors = [
    "Наследование методов суперкласса"
]
context = """
Rust содержит объекты (т.е. структуры) и инкапсуляцию (через ключевое слово `pub`), но не поддерживает наследование.
"""