[[questions]]
id = "35e59c95-3d83-4277-8d88-a1986f4086d7"
type = "MultipleChoice"
prompt.prompt = """
Рассмотрим сопоставление с образцом для выражения некоторого типа `T`.
Какое из этих утверждений лучше всего описывает разницу между опровержимым и неопровержимым образцом?
"""
answer.answer = "Опровержимые образцы не соответствуют некоторому значению типа `T`, в то время как неопровержимые образцы соответствуют всем значениям типа `T`"
prompt.distractors = [
    "Опровержимые образцы соответствуют некоторым значениям другого типа `S`, в то время как неопровержимые образцы соответствуют только значениям типа `T`",
    "Опровержимые образцы не соответствуют никаким значениям типа `T`, в то время как неопровержимые образцы соответствуют некоторым значениям типа `T`",
    "Опровержимые образцы — это образцы, где `T` является перечислением, а неопровержимые образцы — это образцы, где `T` не является перечислением"
]
context = """
Образец является опровержимым, если существует некоторое значение ожидаемого типа, которое не соответствует образцу.
"""

[[questions]]
id = "3c29eb2d-cbe9-4a2c-99b8-aa5c6467c8b4"
type = "MultipleChoice"
prompt.prompt = """
Рассмотрим следующую программу:

```
let x: &[(i32, i32)] = &[(0, 1)];
```

Какие из следующих являются **опровержимыми** образцами для `x`?
"""
answer.answer = [
    "`&[(x, y)]`",
    "`&[(x, y), ..]`",    
]
prompt.distractors = [
    "`&[..]`",
    "`_`"
]
context = """ 
Срез не имеет фиксированной длины, поэтому любой образец, который утверждает, что
`x` должен содержать как минимум один элемент, является опровержимым.
"""