[[questions]]
id = "5dcd923f-13a4-4181-b252-4b580547249f"
type = "Tracing"
prompt.program = """
fn main() {
    let x = (0, 1);
    match x {
        (_, y) if y == 0 => println!("A"),
        (0, _) => println!("B"),
        _ => println!("C")
    }
}
"""
answer.doesCompile = true
answer.stdout = "B"
context = """
Первая ветка соответствует `y = 1`, что означает `y != 0`, поэтому образец не срабатывает.
Вторая ветка требует, чтобы `x == 0`, что истинно, поэтому образец succeeds.
"""

[[questions]]
id = "ac0045c7-981a-46cb-baeb-adaa533804ad"
type = "MultipleChoice"
prompt.prompt = """
Рассмотрим следующую программу:

```
let a = [(0, 1)];
let ?? = a;
```

Какие из следующих образцов являются допустимыми и могут заменить заполнитель `??`?
"""
answer.answer = [
    "`_`",
    "`[(n, ..)]`",
    "`[..]`"
]
prompt.distractors = [
    "`(_, n)`"
]
context = """ 
Образец `(_, n)` недопустим, поскольку `a` — это массив кортежей, а не сам кортеж.
"""

[[questions]]
id = "0b0d90c3-c81b-4b81-9e1b-f8bd58a22c6c"
type = "Tracing"
prompt.program = """
fn main() {
    let x = Some(&[0, 1]);
    match x {
        Some(&[.., 1, ..]) => println!("A"),
        Some(&[0, 1]) | None => println!("B"),
        _ => println!("C")
    }
}
"""
answer.doesCompile = false
answer.lineNumber = 4
context = """
Нельзя использовать `..` с обеих сторон значения, поскольку это неоднозначно — какой именно элемент массива имеется в виду.
"""

[[questions]]
id = "a7d38ffa-66b2-472a-90a5-b026b28ad3df"
type = "MultipleChoice"
prompt.prompt = """
Предположим, у нас есть тип `Point` со следующим определением:

```
struct Point {
    x: i32,
    y: i32
}
```

Учитывая следующий образец:

```
Point { x: x @ 0 ..= 5, y } if x + y != 0
```

Какие из следующих значений соответствуют этому образцу?
"""
answer.answer = [
    "`Point { x: 5, y: -4 }`",
    "`Point { x: 0, y: 1 }`",
]
prompt.distractors = [
    "`Point { x: -1, y: 2 }`",
    "`Point { x: 3, y: -3 }`"
]
context = """
Этот образец указывает, что `x` должен находиться в диапазоне от 0 до 5 (включительно) и что `x + y != 0`.
Следовательно `(5, -4)` и `(0, 1)` являются допустимыми, а `(-1, 2)` и `(3, -3)` — нет.
"""