[[questions]]
id = "f08ab588-1dca-438e-8108-a1b2410a4343"
type = "MultipleChoice"
prompt.prompt = """
Рассмотрим реализацию функции `register`, которая принимает обратный вызов двумя способами:

```
fn register1(cb: fn(Event) -> ());
fn register2<F>(cb: F) where F: Fn(Event) -> ();
```

Какой тип сигнатуры позволяет `register` принимать самый широкий спектр аргументов?
"""
answer.answer = "`register2`"
prompt.distractors = [
  "`register1`",
  "Они эквивалентны"
]
context = """
Замыкания с окружением можно передавать в `register2`, в то время как только функции верхнего уровня (или замыкания без окружения) можно передавать в `register1`.
"""