[[questions]]
id = "8c80f9e8-2d95-43cc-9aa4-04d617dd8cb9"
type = "Tracing"
prompt.program = """
macro_rules! manylet {
    ( $( $i:ident ),* = $e:expr ) => {
        $(
            let mut $i = $e;
        )*
    }
}

fn main() {
    let mut s = String::from("A");
    manylet!(x, y = s);
    x.push_str("B");
    println!("{x}{y}");
}
"""
answer.doesCompile = false
answer.lineNumber = 11
context = """
Макрос `manylet` синтаксически дублирует выражение `e` в качестве привязки для каждой
переменной в левой части знака равенства. Однако, поскольку `s` является владеемой строкой,
первая привязка к `x` перемещает `s`, а вторая привязка к `y` является некорректной.
"""

[[questions]]
id = "f4f664ef-4b0b-43ac-ba90-5051a4ef89fb"
type = "MultipleChoice"
prompt.prompt = """
Какие из перечисленных являются действительными причинами реализации макроса как
процедурного макроса вместо декларативного?
"""
answer.answer = [
    "Вы хотите интегрироваться с системой derive Rust",
    "Ваш макрос требует нетривиальный анализа синтаксиса пользователя макроса",
]
prompt.distractors = [
  "Вы хотите генерировать последовательности кода переменной длины",
  "Ваш макрос требует весь элемент на входе, а не только выражение"
]
context = """
Процедурные макросы — единственный способ создать пользовательский derive. Процедурные макросы
также полезны, когда вам нужно, чтобы код анализировал синтаксис пользователя макроса — декларативные
макросы позволяют только перемещать входные данные, а не, например, вычислять их размер.

Декларативные макросы могут генерировать последовательности кода переменной длины и могут оборачивать/создавать
элементы, а не только выражения.
"""

[[questions]]
id = "4c7dce03-99c6-41e3-8482-ccf4e30974ff"
type = "MultipleChoice"
prompt.prompt = """
Что лучше всего описывает входные данные процедурного макроса? 
"""
answer.answer = "Входными данными является последовательность токенов"
prompt.distractors = [
  "Входными данными является типизированный граф потока управления",
   "Входными данными является абстрактное синтаксическое дерево",
  "Входными данными является байтовая строка"
]
context = """
Процедурные макросы принимают в качестве входных (и производят в качестве выходных) потоки токенов.
Вы можете использовать крейты, такие как `syn`, чтобы преобразовать токены в синтаксические деревья.
"""