[[questions]]
id = "d172fc53-0220-4ff4-83c9-9c0a6834dd8e"
type = "MultipleChoice"
prompt.prompt = "Что такое 1 + 1? (Попробуйте нажать неправильный ответ.)"
answer.answer = "2"
prompt.distractors = [ "0", "-999", "11" ]
context = """
См. *Principia Mathematica* для объяснения этого факта.
"""